### ISSUE TITLE
Fehlende Unterstützung des Farbschemas (Admin5)

### ISSUE THREAD

**Issue by crunchip77** [DrozmotiX/ioBroker.esphome#104]
Admin 5 Farbschema wird noch nicht unterstützt, da viele das dunkle Design bevorzugen, wäre das wünschenswert, wenn möglich

**Comment by Jey-Cee** [comment]
Tab oder Konfiguration? 
Im Tab wird es nicht umsetzbar sein, weil das eine externe Seite ist.

**Comment by crunchip77** [comment]
ok, externe Seite verstehe ich, dann zumindest die Konfigurationsseite, wenn möglich, da sie ja zu Iobroker gehört.

**Comment by DutchmanNL** [comment]
jup, offene Baustelle währe die config in react um zu bauen pro dafuer eher niedrig da alles funktioniert.
Wen admin 5 auch von den Material html den darkmode unterstützen würde hätten wir das problem nicht aber leider ... :)

hab von bug nach enhancement gesetzt, ist kein bug...

**Comment by crunchip77** [comment]
alles gut, war ja mehr oder weniger nur ein Hinweis(Merker) um darauf Aufmerksam zu machen.

**Comment by DutchmanNL** [comment]
solved in neuer admin version >= 5.1.28 (noch beta)
