### ISSUE TITLE
Fehler bei Installation

### ISSUE THREAD

**Issue by NMCity** [DrozmotiX/ioBroker.esphome#105]
Bei der Installation kommt es zu folgenden Fehler:

$ iobroker url https://github.com/DrozmotiX/ioBroker.esphome --host legion-iobroker --debug

install DrozmotiX/ioBroker.esphome#a1f9adad9bfa6b6de20de3c8b293f26b6b44dff5

NPM version: 6.14.14

npm install DrozmotiX/ioBroker.esphome#a1f9adad9bfa6b6de20de3c8b293f26b6b44dff5 --prefix "/opt/iobroker" (System call)

> node-aead-crypto@2.2.1 preinstall /opt/iobroker/node_modules/node-aead-crypto> node lib/preinstall.js

node-aead-crypto not needed on this system, since all ciphers are natively supported

> iobroker.esphome@0.2.4 install /opt/iobroker/node_modules/iobroker.esphome> npip install

No python_modules directory; installing pip locally if needed.

Traceback (most recent call last): File "/opt/iobroker/node_modules/nopy/src/get-pip.py", line 20061, in <module>

main() File "/opt/iobroker/node_modules/nopy/src/get-pip.py", line 194, in main bootstrap(tmpdir=tmpdir) File "/opt/iobroker/node_modules/nopy/src/get-pip.py", line 82, in bootstrap import pip File "/tmp/tmpiab1uogq/pip.zip/pip/__init__.py", line 26, in <module> File "/tmp/tmpiab1uogq/pip.zip/pip/utils/__init__.py", line 23, in <module> File "/tmp/tmpiab1uogq/pip.zip/pip/locations.py", line 9, in <module>ImportError: cannot import name 'sysconfig' from 'distutils' (/usr/lib/python3.7/distutils/__init__.py)

Error: Exited with code 1. at ChildProcess.<anonymous> (/opt/iobroker/node_modules/nopy/src/api.js:277:20)

at ChildProcess.emit (events.js:400:28) at maybeClose (internal/child_process.js:1055:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

npm WARN typedoc@0.20.28 requires a peer of typescript@3.9.x || 4.0.x || 4.1.x but none is installed. You must install peer dependencies yourself.

npm WARN typedoc@0.20.28 requires a peer of typescript@3.9.x || 4.0.x || 4.1.x but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman/node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman-converters/node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.2.1 (node_modules/node-aead-crypto):

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.2.1 preinstall: `node lib/preinstall.js`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! iobroker.esphome@0.2.4 install: `npip install`npm ERR! Exit status 1

npm ERR! npm ERR! Failed at the iobroker.esphome@0.2.4 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2021-09-14T22_08_09_804Z-debug.log

host.legion-iobroker Cannot install DrozmotiX/ioBroker.esphome#a1f9adad9bfa6b6de20de3c8b293f26b6b44dff5: 1

ERROR: Process exited with code 25

**Versions:**  
 - Adapter version: 0.2.4
 - JS-Controller version: 3.3.15
 - Node version: v14.17.5
 - Operating system: debian bullseye

Auszug aus IoBroker Systeminformationen: 

Kernel-release          5.11.22-4-pve
Node.js version        14.17.5
v8-version                8.4.371.23-node.76
NPM version            6.14.14
Git-version               2.30.2
Postfix-version         3.5.6
Perl-version             5.32.1
Python version        2.7.16
Python 3 version     3.9.2
GCC version            10.2.1 20210110
Bash-Version           5.1.4
os.pip                      20.3.4
os.pip3                    20.3.4

**Comment by DutchmanNL** [comment]
Sieht aus alsob er nicht mit deinem Python Version umgehen kan der Fehler kommt von npip, fixer mal probiert ?

**Comment by NMCity** [comment]
Versucht, mit gleichem Ergebniss.

**Comment by santa81** [comment]
Was hast du denn überhaupt für ein grundsystem am laufen, welche Versionen sind da aktiv?

**Comment by Apollon77** [comment]
Ok, mal generell ... google nach der meldung

Ergebnisse:
https://stackoverflow.com/questions/63823964/importerror-cannot-import-name-sysconfig-from-distutils-usr-lib-python3-8

**Comment by NMCity** [comment]
@santa81 Versionen sind oben beschrieben ...
Versions:

Adapter version: 0.2.4
JS-Controller version: 3.3.15
Node version: v14.17.5
Operating system: debian bullseye
Auszug aus IoBroker Systeminformationen:

Kernel-release 5.11.22-4-pve
Node.js version 14.17.5
v8-version 8.4.371.23-node.76
NPM version 6.14.14
Git-version 2.30.2
Postfix-version 3.5.6
Perl-version 5.32.1
Python version 2.7.16
Python 3 version 3.9.2
GCC version 10.2.1 20210110
Bash-Version 5.1.4
os.pip 20.3.4
os.pip3 20.3.4

@Apollon77 
ich hab beide links probiert leider ohne Erfolg.

root@iobroker:~# python3 -V
Python 3.9.2
root@iobroker:~# python3 -c "from distutils import sysconfig"
root@iobroker:~#

**Comment by Apollon77** [comment]
also tried `apt install python3.9-distutils`

**Comment by NMCity** [comment]
jep

**Comment by Apollon77** [comment]
Then I can only state "something is wrong with your local pything installation " :-(

I would prefer if you could open an issue with all details (and ideally referncing to here) on https://github.com/alastairpatrick/nopy/issues ... the adapter can not do anything here

**Comment by NMCity** [comment]
Hey, I was able to solve the problem. The cause was that python3.7-minimal was installed. After removing the package, the installation went through cleanly.

Thanks for your tips

**Comment by DutchmanNL** [comment]
> Hey, I was able to solve the problem. The cause was that python3.7-minimal was installed. After removing the package, the installation went through cleanly.
> 
> Thanks for your tips

great thanks you for your feedback, I will mark this issue als good question to help others :)!
