### ISSUE TITLE
status is wrong

### ISSUE THREAD

**Issue by arteck** [DrozmotiX/ioBroker.esphome#106]
online status is wrong in objects
![grafik](https://user-images.githubusercontent.com/6681528/134956514-4c14a96d-36e4-482f-95b9-82baf3537b31.png)

wifi: 
power_save_mode: none

**Comment by DutchmanNL** [comment]
is the ESP really offline or only shown in dashboard offline ?
The dashboard needs MNDS for its query, adapter user direct IP & socket connection I have seen this couple of time in situations with VLAN's

**Comment by arteck** [comment]
its REALLY OFFLINE..

**Comment by maxpd1** [comment]
Same here:

The Online status is shown different in the instance view compared with object view:

the connection attribute is always indicated with true even if I turn of the ESP.
The _online attribute stays false even if esp is online and marked as online in instance view

![image](https://user-images.githubusercontent.com/15956503/159007977-ea6b73ab-ae06-42b6-8cd6-50f70cbb5b52.png)



The ESP script looks like this

`esphome:
name: little_wemos
platform: ESP8266
board: d1_mini

wifi:
ssid: !secret wifi_ssid
password: !secret wifi_password

Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
ssid: "Little Wemos Fallback Hotspot"
password: "************"

captive_portal:

Enable logging
logger:

api:
services:
- service: control_servo
variables:
level: float
then:
- servo.write:
id: my_servo
level: !lambda 'return level / 1000.0;'

ota:

output:

platform: esp8266_pwm
id: pwm_output
pin: D3
frequency: 50 Hz
servo:

id: my_servo
output: pwm_output
`

**Comment by DutchmanNL** [comment]
feeler gefunden und korrigiert, wird in v0.3.1 released. Das problem trat auf wen ein ESP im betrieb des adapters online war, der adapter abgeschaltet wurde, der ESP getrennt und dan der adapter gestartet dabei hat er die online states nicht richtig mitgenommen.

Um das zu vermeiden habe ich:

- sicher gestellt das der online status beim stoppen und starten des adapter auf FALSE gesetzt wird
- Bei der Gelegenheit den online status sichtbar in den objecten eingebaut
