### ISSUE TITLE
Kann ESPHome in iobroker nicht installieren

### ISSUE THREAD

**Issue by ThomasLoeffel** [DrozmotiX/ioBroker.esphome#107]
Hallo Zusammen,

ich habe keine Ahnung was ich machen soll. 

Danke und sorry für ggf. unnötige Verwirrung.
Thomas

![image](https://user-images.githubusercontent.com/44590735/136667024-cb0c2a60-a010-4f87-9756-3452a61390de.png)

**Comment by DutchmanNL** [comment]
Welche Python Version hast du drauf?

**Comment by ThomasLoeffel** [comment]
Ich bin da eher neu. Habe im VM (Synology) Ubuntu mit iobroker. Wo soll Python installiert sein? Sorry für die Frage.

**Comment by ThomasLoeffel** [comment]
Mit dem Befehl Ubuntu: python --version

Kommt: Python 2.7.17

**Comment by ThomasLoeffel** [comment]
Zusatz:
python3 --version
Python 3.6.9
