### ISSUE TITLE
Mit Synology / iobroker / esphome kann ich nicht über USB flashen.....

### ISSUE THREAD

**Issue by ThomasLoeffel** [DrozmotiX/ioBroker.esphome#108]
System:
Synology -> VM Ubuntu mit iobroker und ESPhome
Zusatz -> USB-3.0 Kabel 3 m lang

Details: [forum.iobroker.net/topic/42741/esphome-beta-release/327](url)
Habe auch überprüft ob die USB vom Synology zur Ubuntu VM reicht. Funktioniert über Tasmotizer und meinem Desktop (mit der aus Esphome im Download gespeicherten xyz.bin).

Gruß Thomas

**Comment by DutchmanNL** [comment]
Wüsste nicht was ich hieran machen kan, das ist zu specifisch für ne synology nas kan an allem möglichen liegen.

eonmal die bin per PC Flaschen danach per Geht ja PTA währe meine Empfehlung
