### ISSUE TITLE
Support for AZ-Delivery D1 R32

### ISSUE THREAD

**Issue by Beliar-666** [DrozmotiX/ioBroker.esphome#111]
**Describe wanted Enhancement !**  
I suggest to implemetn the Az-Delivery Board D1 R32  Wifi&Bluetooth R32 Based on ESP32 Wroom-32

**Why should we put effort in it ?**  
With using one of the implemented Boards the D1 R32 will not connect to Wifi correctly.

**Comment by santa81** [comment]
Bitte direkt bei esphome anfragen, entweder dort unter issues oder [hier](https://github.com/esphome/feature-requests)

**Comment by DutchmanNL** [comment]
Danke @santa81, stimmt der ioBroker Adapter kan da nichts dran ändern müsste in ESPHome geschehen
