### ISSUE TITLE
Slave installation Error: required adapter "admin" not found!

### ISSUE THREAD

**Issue by marsmaennchen** [DrozmotiX/ioBroker.esphome#112]
When i try to install the Adapter on my IoBroker Slave the Error `<html>
<body>

host.achbotslave | 2021-11-21 15:22:20.996 | error | startInstance system.adapter.esphome.0: required adapter "admin" not found!
-- | -- | -- | --

</body>
</html>
`
is shown.

**Comment by Apollon77** [comment]
@DutchmanNL Put admin dep into gobalDependencies!

**Comment by DutchmanNL** [comment]
> @DutchmanNL Put admin dep into gobalDependencies!

Thanks! @marsmaennchen will make a new Package Version this week just need to restore a little from sickness grrr stupid flu period 🤧

**Comment by lobomau76** [comment]
I have installed another admin instance that runs on the slave. Works fine with the adapters ESPHome and admin on the slave (Pi4)
