### ISSUE TITLE
Dashboard and admin with https 

### ISSUE THREAD

**Issue by Jey-Cee** [DrozmotiX/ioBroker.esphome#113]
**!!! Before you start !!!**  
1. Verify if there is not already an issue requesting the same -> CHECK
2. Is this really a bug of current code, or an enhancement request ? -> CHECK

**Describe the bug**  
If the https feature in admin is enabled, the built in Dashboard of ESPHome can not be shown inside the admin.

**To Reproduce**  
1. Go to admin config
2. Click on HTTPS
3. Save and exit
4. Try to open ESPHome in admin

**Expected behavior**  
The EPSHome Dashboard should use also https, if the admin uses https.

**Versions:**  
 - Adapter version: 0.2.4
 - JS-Controller version: 3.3.21
 - Node version: 14.18.2
 - Operating system: Ubuntu server

**Additional context**  
The issue is a security policy problem, while a site with https can not load content from a http only site.

**Comment by mgernhard** [comment]
Any ideas when there will be a stable version?

Will it support a broker as well like in HA or will it only be a connection only?

**Comment by turbolift** [comment]
Running esphome on port 6052 with tls and iobroker admin on port 443 with tls.

Klicking on Tab esphome (https://192.168.178.17/#tab-esphome-0) I get:

`Mixed Content: The page at 'https://192.168.178.17/#tab-esphome-0' was loaded over HTTPS, but requested an insecure frame 'http://192.168.178.17:6052/?instance=0&newReact=true&0&react=colored'. This request has been blocked; the content must be served over HTTPS.`

**Comment by DutchmanNL** [comment]
> Running esphome on port 6052 with tls and iobroker admin on port 443 with tls.
> 
> Klicking on Tab esphome (https://192.168.178.17/#tab-esphome-0) I get:
> 
> `Mixed Content: The page at 'https://192.168.178.17/#tab-esphome-0' was loaded over HTTPS, but requested an insecure frame 'http://192.168.178.17:6052/?instance=0&newReact=true&0&react=colored'. This request has been blocked; the content must be served over HTTPS.`

esphome dashboard does not support https I cannot change that
