### ISSUE TITLE
keine installation möglich

### ISSUE THREAD

**Issue by denjo1982** [DrozmotiX/ioBroker.esphome#120]
Adapter lässt sich nicht installieren, bekomme immer folgende fehlermeldung im log: `$ iobroker url https://github.com/DrozmotiX/ioBroker.esphome.git --host raspberrypi

install DrozmotiX/ioBroker.esphome#86201d5e87abede6071e84b38299bb72f699fef0

NPM version: 6.14.15

npm install DrozmotiX/ioBroker.esphome#86201d5e87abede6071e84b38299bb72f699fef0 --loglevel error --prefix "/opt/iobroker" (System call)

Cache entry deserialization failed, entry ignored

Cache entry deserialization failed, entry ignored

error: subprocess-exited-with-error × pip subprocess to install build dependencies did not run successfully. │ exit code: 1 ╰─> [70 lines of output] Collecting setuptools>=40.6.0 Using cached setuptools-60.9.1-py3-none-any.whl (1.1 MB) Collecting wheel Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB) Collecting cffi>=1.12 Using cached cffi-1.15.0.tar.gz (484 kB) Preparing metadata (setup.py): started Preparing metadata (setup.py): finished with status 'done' Collecting setuptools-rust>=0.11.4 Using cached setuptools_rust-1.1.2-py3-none-any.whl (21 kB) Collecting pycparser Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB) Collecting typing-extensions>=3.7.4.3 Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB) Collecting semantic-version<3,>=2.8.2 Using cached semantic_version-2.9.0-py2.py3-none-any.whl (15 kB) Building wheels for collected packages: cffi Building wheel for cffi (setup.py): started Building wheel for cffi (setup.py): finished with status 'error' error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [10 lines of output] running bdist_wheel running build running build_py running build_ext building '_cffi_backend' extension c/_cffi_backend.c:2:10: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden 2 | #include <Python.h> | ^~~~~~~~~~ compilation terminated. error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for cffi Running setup.py clean for cffi Failed to build cffi Installing collected packages: wheel, typing-extensions, setuptools, semantic-version, pycparser, setuptools-rust, cffi Running setup.py install for cffi: started Running setup.py install for cffi: finished with status 'error' error: subprocess-exited-with-error × Running setup.py install for cffi did not run successfully. │ exit code: 1 ╰─> [12 lines of output] running install /opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running build running build_py running build_ext building '_cffi_backend' extension c/_cffi_backend.c:2:10: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden 2 | #include <Python.h> | ^~~~~~~~~~ compilation terminated. error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure × Encountered error while trying to install package. ╰─> cffi note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip.

error: subprocess-exited-with-error× pip subprocess to install build dependencies did not run successfully.│ exit code: 1╰─> See above for output.note: This error originates from a subprocess, and is likely not a problem with pip.

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! iobroker.esphome@0.2.4 install: `npip install`npm ERR! Exit status 1

npm ERR! npm ERR! Failed at the iobroker.esphome@0.2.4 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2022-02-15T17_05_33_774Z-debug.log

host.raspberrypi Cannot install DrozmotiX/ioBroker.esphome#86201d5e87abede6071e84b38299bb72f699fef0: 1

ERROR: Process exited with code 25`

**Comment by DutchmanNL** [comment]
welche python version haste drauf ?

**Comment by denjo82** [comment]
Muss man python installieren? Wenn ja wie installiere ich das auf ein raspi mit iobroker?

**Comment by DutchmanNL** [comment]
> Muss man python installieren? Wenn ja wie installiere ich das auf ein raspi mit iobroker?

jup siehe readme ist eine pre-requesite :)

```
* NodeJS >= 12.x
* Python >=3.7, <4.0
* API is activated in YAML
* For admin tabs (optional)
    * ESPHome Dashboard IP is provided in instance settings
```

Lass uns erstmal schauen. ob du irgendein Python installiert hast Raspbian liefert das eigentlich standard.
Was kommt auf der console. we du diese befehle ausfuehrst ?

```
python --version
python2 --version
python3 --version
```

**Comment by denjo1982** [comment]
Python 2.7.18
Python 2.7.18
Python 3.9.2

**Comment by PhagoZ** [comment]
Hey, habe auch Probleme bei der Installation.
Node und Python sind beide innerhalb der specs.
(node 14.x, Python 3.9.5)
ich habe sogar die Standardverknüpunf von python (bei dem die Versionsabfrage 2.7.x rausgibt) auf 3.9.5 geändert.

was hat es mit der API Vorgabe auf sich?? ich finde dazu keinerlei Infos.

Werde aus dem Fehlerbericht nicht schlau :(

Fertig mit Fehler: host.raspberrypi Cannot install DrozmotiX/ioBroker.esphome#86201d5e87abede6071e84b38299bb72f699fef0: 1

Collecting cryptography>=2.1.4
  Using cached cryptography-36.0.1.tar.gz (572 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error    × pip subprocess to install build dependencies did not run successfully.  │ exit code: 1  ╰─> [122 lines of output]      Collecting setuptools>=40.6.0        Using cached setuptools-60.9.2-py3-none-any.whl (1.1 MB)      Collecting wheel        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)      Collecting cffi>=1.12        Using cached cffi-1.15.0.tar.gz (484 kB)        Preparing metadata (setup.py): started        Preparing metadata (setup.py): finished with status 'done'      Collecting setuptools-rust>=0.11.4        Using cached setuptools_rust-1.1.2-py3-none-any.whl (21 kB)      Collecting pycparser        Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)      Collecting typing-extensions>=3.7.4.3        Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)      Collecting semantic-version<3,>=2.8.2        Using cached semantic_version-2.9.0-py2.py3-none-any.whl (15 kB)      Building wheels for collected packages: cffi        Building wheel for cffi (setup.py): started        Building wheel for cffi (setup.py): finished with status 'error'        error: subprocess-exited-with-error              × python setup.py bdist_wheel did not run successfully.        │ exit code: 1        ╰─> [36 lines of output]            running bdist_wheel            running build            running build_py            creating build            creating build/lib.linux-armv7l-3.7            creating build/lib.linux-armv7l-3.7/cffi            copying cffi/error.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/cparser.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/vengine_gen.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/verifier.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/ffiplatform.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/api.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/lock.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/model.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/pkgconfig.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/__init__.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/commontypes.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/recompiler.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/_cffi_include.h -> build/lib.linux-armv7l-3.7/cffi            copying cffi/parse_c_type.h -> build/lib.linux-armv7l-3.7/cffi            copying cffi/_embedding.h -> build/lib.linux-armv7l-3.7/cffi            copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-3.7/cffi            running build_ext            building '_cffi_backend' extension            creating build/temp.linux-armv7l-3.7            creating build/temp.linux-armv7l-3.7/c            arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.7/c/_cffi_backend.o            c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory             #include <Python.h>                      ^~~~~~~~~~            compilation terminated.            error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1            [end of output]              note: This error originates from a subprocess, and is likely not a problem with pip.        ERROR: Failed building wheel for cffi        Running setup.py clean for cffi      Failed to build cffi      Installing collected packages: wheel, typing-extensions, setuptools, semantic-version, pycparser, setuptools-rust, cffi        Running setup.py install for cffi: started        Running setup.py install for cffi: finished with status 'error'        error: subprocess-exited-with-error              × Running setup.py install for cffi did not run successfully.        │ exit code: 1        ╰─> [38 lines of output]            running install            /opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.              setuptools.SetuptoolsDeprecationWarning,            running build            running build_py            creating build            creating build/lib.linux-armv7l-3.7            creating build/lib.linux-armv7l-3.7/cffi            copying cffi/error.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/cparser.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/vengine_gen.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/verifier.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/ffiplatform.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/api.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/lock.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/model.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/pkgconfig.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/__init__.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/commontypes.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/recompiler.py -> build/lib.linux-armv7l-3.7/cffi            copying cffi/_cffi_include.h -> build/lib.linux-armv7l-3.7/cffi            copying cffi/parse_c_type.h -> build/lib.linux-armv7l-3.7/cffi            copying cffi/_embedding.h -> build/lib.linux-armv7l-3.7/cffi            copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-3.7/cffi            running build_ext            building '_cffi_backend' extension            creating build/temp.linux-armv7l-3.7            creating build/temp.linux-armv7l-3.7/c            arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.7/c/_cffi_backend.o            c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory             #include <Python.h>                      ^~~~~~~~~~            compilation terminated.            error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1            [end of output]              note: This error originates from a subprocess, and is likely not a problem with pip.      error: legacy-install-failure            × Encountered error while trying to install package.      ╰─> cffi            note: This is an issue with the package mentioned above, not pip.      hint: See above for output from the failure.      [end of output]    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error× pip subprocess to install build dependencies did not run successfully.│ exit code: 1╰─> See above for output.note: This error originates from a subprocess, and is likely not a problem with pip.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman/node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman-converters/node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLEnpm ERR! errno 1
npm ERR! iobroker.esphome@0.2.4 install: `npip install`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the iobroker.esphome@0.2.4 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2022-02-16T19_46_02_219Z-debug.log
ERROR: host.raspberrypi Cannot install DrozmotiX/ioBroker.esphome#86201d5e87abede6071e84b38299bb72f699fef0: 1
ERROR: process exited with code 25

**Comment by PhagoZ** [comment]
Hab das Problem gelöst.
Der Adapter installiert pip nicht mit.

[https://www.codegrepper.com/code-examples/shell/install+pip+on+raspberry+pi](url)

**Comment by denjo82** [comment]
Bedeutet?

**Comment by PhagoZ** [comment]
Du gehst über putty auf deinen RPi und installierst pip manuell wie im Link beschrieben.
ich hab pip3 gleich auch installiert. Keine Ahnung ob notwendig

**Comment by DutchmanNL** [comment]
> Hab das Problem gelöst. Der Adapter installiert pip nicht mit.
> 
> [https://www.codegrepper.com/code-examples/shell/install+pip+on+raspberry+pi](url)

hmm danke, pip ist eigentlich standard dabei wen man python installiert.
Realisiere mir aber gerade das die nur auf Debian like Linux der fall ist wen man ueber apt installiert.

Ich werde es als Requirement aufnehmen da ich leider die installation von python und pip nicht mit dem adapter beeinflussen kan (ist auch ungewollt, ein adapter sollte nicht auf dem system installieren/aendern ausserhalb ioBrokers.

Ich markiere das issue als docu und lassen es offen bis das realisiert ist

Viele dank fuer euer feedback ich hätte hier bestimmt lange gesucht und nach tagen mal einen neues system aufgehest und erst dan das pip problem entdeckt !

**Comment by Christiapb** [comment]
Frohes Neues Jahr!
Habe Probleme ESPHome zu installieren. Endet mit error25.

Der Link zur installation von "pip" endet bei einer leeren Seite, und habe desshalb pip so installiert:
sudo apt update
sudo apt install python3-pip

und bekomme:
pip3 --version
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)

Was kann ich noch versuchen um den ESPHomeadapter zu installieren?

Hab noch kein ESP mit ESPHome auf dem Netzwerk.

Gruss
Christian

**Comment by djanknecht** [comment]
@Christiapb Ich habe den Adapter installiert bekommen - mit "sudo iobroker install ioBroker.esphome" 
Vorher pip3 installiert 
"sudo apt-get install python3-pip"

**Comment by Christiapb** [comment]
Danke dir @djanknecht !

Die installation von pip3 hatte ich schon gemacht, ist in Ordnung, glaube ich.
Die installation von ESPhome aber nicht.
Was mache ich falsch?



pi@raspberrypi:~ $ sudo apt-get install python3-pip
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (20.3.4-4+rpt1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 53 not upgraded.
pi@raspberrypi:~ $ sudo iobroker install ioBroker.esphome
host.raspberrypi Unknown packetName esphome. Please install packages from outside the repository using npm!
pi@raspberrypi:~ $

**Comment by djanknecht** [comment]
Hi, hast Du den Channel auf Beta gestellt?

27.02.2023 10:58:16 Christiapb ***@***.***>:

**Comment by djanknecht** [comment]
Im Admin Gui vom ioBroker

27.02.2023 11:15:01 Christiapb ***@***.***>:

**Comment by Christiapb** [comment]
pi@raspberrypi:~ $ sudo iobroker install ioBroker.esphome
NPM version: 8.19.2
Installing iobroker.esphome@0.2.4... (System call)
host.raspberrypi Cannot install iobroker.esphome@0.2.4: 126


Das ESPhome -ikon ist jetzt aber im ioBroker sichtbar. Endet aber immer noch so:

ERROR: Process exited with code 25
less
more
$ iobroker add esphome auto --host raspberrypi --debug

NPM version: 8.19.2

Installing iobroker.esphome@0.2.4... (System call)

npm ERR! code 126

npm ERR! sh: 1: npip: Permission denied

npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2023-02-27T10_27_22_476Z-debug-0.log

host.raspberrypi Cannot install iobroker.esphome@0.2.4: 126

ERROR: Process exited with code 25

**Comment by Fix1985** [comment]
Ich habe leider genau die gleiche Fehlermeldung wie Christiapb
Kann uns hierbei vielleicht jemand helfen?
Im Log steht leider nichts drin.
