### ISSUE TITLE
Deep Sleep Error Meldung

### ISSUE THREAD

**Issue by Draexl** [DrozmotiX/ioBroker.esphome#121]
Ich nutze die Deep Sleep Funktion. Dementsprechend habe ich Error Meldungen im ioBroker Log das der ESP nicht erreichbar ist.
Kann man das unterbinden? Eventuell durch eine Auswahlmöglichkeit in der Administration das dieser Error nicht ausgegeben werden soll?

**Comment by DutchmanNL** [comment]
> Ich nutze die Deep Sleep Funktion. Dementsprechend habe ich Error Meldungen im ioBroker Log das der ESP nicht erreichbar ist.
> Kann man das unterbinden? Eventuell durch eine Auswahlmöglichkeit in der Administration das dieser Error nicht ausgegeben werden soll?

gute idee, ich schaue mir mal an was man damit machen könnten.
eventuell nur eine Meldung ausgeben, muss mir anschauen ob ich vom ESP daten bekomme die melden das er deepsleep konfiguriert hat dan kan ich das komplett im code abfangen

**Comment by Draexl** [comment]
Eigentlich wäre es wie du es beschrieben hast ja schon die Musterlösung.
Der DeepSleep Cycle ist aber ein guter Punkt. Wäre es möglich in den Adaptereinstellungen einen individuellen Wert in Minuten zu hinterlegen?
Beispiel:
In der Regel wird ja der Deep Sleep verwendet wegen Batteriebetrieb. In meinen Fall alle 10 Minuten. In der beschriebenen Adaptereinstellung habe ich festgelegt das eine Error Meldung ausgegeben werden wenn 30 Minuten lang keine Rückmeldung kam. Wenn dadurch eventuell sogar noch ein Datenpunkt (z.B. Missing ESP) mit false gesetzt würde, den ich per Script auswerten könnte wäre das ja ein Traum. Damit könnte z.B. eine Nachricht verschickt werden "ESP XY hat sich nicht mehr gemeldet, bitte Batterien überprüfen" oder so ähnlich.

**Comment by DutchmanNL** [comment]
> Wenn dadurch eventuell sogar noch ein Datenpunkt (z.B. Missing ESP) mit false gesetzt würde, den ich per Script auswerten könnte wäre das ja ein Traum. Damit könnte z.B. eine Nachricht verschickt werden "ESP XY hat sich nicht mehr gemeldet, bitte Batterien überprüfen" oder so ähnlich.

genau das war mein Gedanke, ich schaue es mir mal an ob ich vom ESP die werte des deepsleep bekomme kan.
wen ja kan ich die online/offline routine abfangen, momentan haben wir einen wert "online", ich könnte mir vorstellen einen weet isSleeping hinzu zu fuegeen... muss mal biss nachdenken wie wir das am besten in die states einfliessen lassen aber Grundgedanke verstanden !

**Comment by DutchmanNL** [comment]
> Eigentlich wäre es wie du es beschrieben hast ja schon die Musterlösung. Der DeepSleep Cycle ist aber ein guter Punkt. Wäre es möglich in den Adaptereinstellungen einen individuellen Wert in Minuten zu hinterlegen? Beispiel: In der Regel wird ja der Deep Sleep verwendet wegen Batteriebetrieb. In meinen Fall alle 10 Minuten. In der beschriebenen Adaptereinstellung habe ich festgelegt das eine Error Meldung ausgegeben werden wenn 30 Minuten lang keine Rückmeldung kam. Wenn dadurch eventuell sogar noch ein Datenpunkt (z.B. Missing ESP) mit false gesetzt würde, den ich per Script auswerten könnte wäre das ja ein Traum. Damit könnte z.B. eine Nachricht verschickt werden "ESP XY hat sich nicht mehr gemeldet, bitte Batterien überprüfen" oder so ähnlich.

Where es möglich deine yaml mit dem deep sleep settings zu teilen damit ich mal schauen kan ohne das Rad selber neu zu erfinden mit der yaml config ?

**Comment by Draexl** [comment]
Hi, du ich habe es anders gelöst. Es gibt wenn man DeepSleep nutzt in den Datenpunkten bereits den Punkt DeepSleep. Auf dem lasse ich dann einfach ein Blocklyscript laufen das die Zeit zwischen true und false misst.
Eigentlich kann dieser Issue geschlossen werden.
