### ISSUE TITLE
Error Meldung Cannot read property 'connectError' of undefined`

### ISSUE THREAD

**Issue by Draexl** [DrozmotiX/ioBroker.esphome#123]
Hi,
ich habe bei mir alles geupdatet und habe nun Massenweise folgende Error Meldungen im Log:

`ESPHome error handling issue 192.168.1.63 TypeError: Cannot read property 'connectError' of undefined`

ESPHOME Version: v2022.2.3
Adapterversion: v0.2.4

Zwischenzeitlich habe ich schon alles deinstalliert, neuinstalliert geflasht etc.

**Comment by Draexl** [comment]
Hi, gibt es schon Neuigkeiten bzw. eine Planung wann das Update kommen wird?

**Comment by DutchmanNL** [comment]
> Hi, gibt es schon Neuigkeiten bzw. eine Planung wann das Update kommen wird?

bitte mit neuer version probieren
