### ISSUE TITLE
TypeError: Cannot read property 'deserializeBinary' of undefined

### ISSUE THREAD

**Issue by Anzic23** [DrozmotiX/ioBroker.esphome#124]
**Describe the bug**  
When adding a configuration from the [Nice_BusT4](https://github.com/pruwait/Nice_BusT4) repository, I get constant errors in the log. In the device log, there are also errors with reconnection from the side of the iobroker.
There is also no way to control the end device, the objects simply do not appear.

**To Reproduce**  
1. just install the config from the repository.
2. See error

**Expected behavior** 
I would like to be able to operate the garage door as a home assistant. Need objects in iobroker.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/155900987-47f330bb-da2e-4868-bdf5-129f8662387b.png)

**Versions:**  
 - Adapter version: 0.2.4
 - JS-Controller version: 3.3.22
 - Node version: v14.19.0
 - Operating system: docker

**Additional context**  
my config:
```
#отправляет пакеты через uart в шину Nice BUS T4
#тест на Wemos D1 mini

esphome:
  name: garage-test
  platform: ESP8266
  board: nodemcuv2


external_components:
  - source:
      type: git
      url: https://github.com/pruwait/Nice_BusT4



# включаем отладку для поиска причины перезагрузки через лог
debug:
    
# Enable logging
logger:
  level: DEBUG
  baud_rate: 0
  
# Enable Home Assistant API
api:
  password: "pasds"
  services:
# для отправки hex команд на привод
  - service: raw_command
    variables:
        raw_cmd: string
    then:
      lambda: |-
         my_nice_cover -> NiceBusT4::send_raw_cmd(raw_cmd);
 
  reboot_timeout: 0s # иначе перезагружается при отключении от hassio  

ota:

# Set statul led for Wemos D1 mini
status_led:
  pin: 
    number: D4
    inverted: true
  


wifi:
  ssid: "Skynet_IoT"
  password:  "piy680zxc"

  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "garage Hotspot"
    password: !secret ota_pass



captive_portal:


# Enable web server (can be disabled)
web_server:
  port: 80


button:
  - platform: template
    name: Open
    id: send_open
    on_press:
      lambda: |-
         my_nice_cover -> NiceBusT4::send_open();
        
        
cover:
- platform: bus_t4
  name: "Nice Wingo 5000"
  id: "my_nice_cover"

```

**Comment by darkman242** [comment]
any news regarding the bug. I can install the adapter, but when I add devices the mentioned error occurs and the connection to the ESP is disconnected (is shown on the ESP in the log and in the adapter instance the device is then on 'red').
