### ISSUE TITLE
ESPHome client connect ECONNREFUSED

### ISSUE THREAD

**Issue by lobomau76** [DrozmotiX/ioBroker.esphome#130]
There is no client installed on 192.168.1.1.
There are two clients working properly on 192.168.30.x
Why does there come this error in log?

esphome.0 | 2022-04-27 13:41:44.246 | error | ESPHome client 192.168.1.1 Error: connect ECONNREFUSED 192.168.1.1:6053
-- | -- | -- | --
esphome.0 | 2022-04-27 13:41:14.244 | error | ESPHome client 192.168.1.1 Error: connect ECONNREFUSED 192.168.1.1:6053
esphome.0 | 2022-04-27 13:40:44.241 | error | ESPHome client 192.168.1.1 Error: connect ECONNREFUSED 192.168.1.1:6053
esphome.0 | 2022-04-27 13:40:14.237 | error | ESPHome client 192.168.1.1 Error: connect ECONNREFUSED 192.168.1.1:6053
esphome.0 | 2022-04-27 13:39:44.234 | error | ESPHome client 192.168.1.1 Error: connect ECONNREFUSED 192.168.1.1:6053
esphome.0 | 2022-04-27 13:39:14.231 | error | ESPHome client 192.168.1.1 Error: connect ECONNREFUSED 192.168.1.1:6053
esphome.0 | 2022-04-27 13:38:44.228 | error | ESPHome client 192.168.1.1 Error: connect ECONNREFUSED 192.168.1.1:6053

Versions:
 - Adapter version: 0.2.4
 - JS-Controller version: 4.0.23
 - Node version: 14.19.1
 - Operating system: debian (master) raspbian (slave)

**Comment by DutchmanNL** [comment]
it looks like the automated device detections finds a MDNS message on that IP I detects as ESPHome device.
Can you please provide complete log of startup for this adapter, you can delete the device in the instanze setting of the adapter and verify if its auto added again

**Comment by lobomau76** [comment]
Ah... automated device detections was turned on. I have turned it off and it seems that error dose not come anymore.
This device I cannot delete because it is not in the list of the adapter.
192.168.1.1 is the IP of the Unifi USG.
