### ISSUE TITLE
[W][api.connection:068]: 10.10.21.30: Socket operation failed: BAD_INDICATOR errno=11

### ISSUE THREAD

**Issue by Armin46** [DrozmotiX/ioBroker.esphome#137]
Hello, 

i have a problem to transmit data from the ESP to the Iobroker.

I use a Nodemcu.

I get on the ESP the meassage `[W][api.connection:068]: 10.10.21.30: Socket operation failed: BAD_INDICATOR errno=11` 

And on the Iobroker `

  | 2022-08-25 15:18:57.104 | warn | Client 10.10.21.60 Timeout, connection Lost, will reconnect automatically when device is available!
esphome.0 | 2022-08-25 15:18:52.124 | error | ESPHome client 10.10.21.60 Error: Bad format. Expected 0 at the begin

**Versions:**  
 - Adapter version: 0.2.4
 - JS-Controller version: 4.0.23
 - Node version: v16.16.0
 - Operating system: bullseye

Thanks in Advance,
Armin

**Comment by SimonFischer04** [comment]
See: https://github.com/DrozmotiX/ioBroker.esphome/issues/155, https://github.com/DrozmotiX/ioBroker.esphome/issues/152
