### ISSUE TITLE
Geräte Doppelt

### ISSUE THREAD

**Issue by Draexl** [DrozmotiX/ioBroker.esphome#139]
Hi, bei mir werden die Geräte in den Adaptereinstellungen doppelt angezeigt.
Eines der beiden ist entweder rot oder grün, währenddessen das andere immer grau ist.
Lösche ich eines von beiden, sind beide weg (Auch in den Objekten)
Ist das bekannt? Was kann ich machen?

Verhalten ist in allen Browsern.

![image](https://user-images.githubusercontent.com/86128006/189163216-9bfefb92-4f82-48e4-99f3-3ebee9a4fdca.jpeg)

**Comment by DutchmanNL** [comment]
Moment besser schauen, dich sind doppelte dabei.

Kannst du mal bitte die yaml Datei zeigen von einem Gerät wo das passiert ?

**Comment by Draexl** [comment]
Also passieren tut dies bei allen Geräten.

Hier mal die kürzere YAML:

`esphome:
  name: aussenbereich-zisterne

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

# OTA
ota:
  password: "daff18659d85c379abf079875b1ff046"

# Enable WIFI
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "aussenbereich-zisterne"
    password: "hoIsmZVbRBMZ"

# Example configuration entry
switch:
  - platform: restart
    name: "Zisterne Distanz Neustart"

##############

captive_portal:

time:
 - platform: sntp
   id: current_time
   timezone: Europe/Berlin
   servers : ptbtime1.ptb.de
   
i2c:
  sda: D2
  scl: D1
   
sensor:
  - platform: vl53l0x
    name: "Distanz"
    address: 0x29
    update_interval: 30s
    long_range: true`

**Comment by Draexl** [comment]
Bin irgendwie zu doof die YAML in Codetags zu packen....

**Comment by DutchmanNL** [comment]
Par fragen 

Adapter Version ?
ESPHome Dashboard Version ?
JS-Controller Version
Admin Version?
Wann installiert

Thanks !

**Comment by Draexl** [comment]
Adapter Version -> v0.2.4
ESPHome Dashboard Version -> v2022.2.6
JS-Controller Version ->v16.17.0
Admin Version -> v6.2.20
Wann installiert-> Welches Datum brauchst du da? ESP läuft schon seit ca. 1 Jahr mit den entsprechenden Updates. Die Updates des Admin, JS, etc. erfolgen eigentlich immer ziemlich Tagesgenau nach erscheinen.

**Comment by DutchmanNL** [comment]
Danke, wurde Februar dieses Jahr installiert sehe ich am ESPHome Dashboard 

Seit wan tritt das Problem auf, doch nicht schon immer oder (könnte etwas mit neuem Admin zubringen haben)

Dienlich Einträge vom starten des Adapter währen auch interessant

**Comment by Draexl** [comment]
Ja, der neue Admim Adapter könnte hinkommen.
Was brauchst du für Info beim Adapterstart? Logs? Welche?

**Comment by Draexl** [comment]
Brauchst du noch was von mir?

**Comment by Draexl** [comment]
Geräte sind wieder einfach da.
Vermute gelöst durch Admin Update
