### ISSUE TITLE
EspHome update

### ISSUE THREAD

**Issue by sevelen** [DrozmotiX/ioBroker.esphome#140]
I´m looking for an option to update the espHome to version  2022.8.3.

Any idea to do it automatic or manual?

**Comment by DutchmanNL** [comment]
- Go to the adapter overview
- Enable expert mode
- look for the Adapter, and install the current Version again
- adapter Version will Stau the Same
- ESPHome dashboard Sjoukje ne Updates
- Susanne expert mode again

Please Provide feedback if it was successfully for you

**Comment by sevelen** [comment]
Not sure what you mean, I check the adapter page and install it by the plus sign again. There after I start the dashbord again and the bottom line still shows v2022.2.6 instead of v2022.8.3?

Any help is appresitated

**Comment by DutchmanNL** [comment]
we will further handle this issue in combination of #118 and try to make an automated release cycle with updates by the admin interface based on versioning
