### ISSUE TITLE
Datapoint not created correclty, true/false datapoint is missing

### ISSUE THREAD

**Issue by Roellen** [DrozmotiX/ioBroker.esphome#142]
Hi. 

I've got a "mmwave" sensor. It works perfectly within home assistant. But I like to use it within iobroker. 
The sensor shows up in the browser and works. 
But there is a problem with the data point in the "objects" section of iobroker. 
There is only a folder but not a real "true/false" datapoint. 

I tried to delete everything, so that the adapter creates it again, but... same problem. 
So I can't use the sensor right now. Not sure how to fix it. 

**Versions:**  
 - Adapter version: v0.2.4
 - JS-Controller version: v16.17.0
 - Node version: 8.15.0
 - Operating system: linux

![mmwave1](https://user-images.githubusercontent.com/69198711/191741866-901e28dd-2e06-44a3-9941-cfef4ed50d2c.jpg)

![mmwave2](https://user-images.githubusercontent.com/69198711/191741888-eeac8574-c2bf-4fbe-9dae-46ed7894f5e2.jpg)

![mmwave3](https://user-images.githubusercontent.com/69198711/191741905-41bb84e8-94b3-404d-b0c7-8325e5118e4d.jpg)

**Comment by DutchmanNL** [comment]
Can you please Share your yaml?
(Please ensire that secrets, like wifi password etc, are Not in your comment 😊)

**Comment by Roellen** [comment]
`esphome:
  name: mmwave-occupancy

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "totoally_secret_you_know..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mmwave Fallback Hotspot"
    password: "totoally_secret_you_know..."

substitutions:
  device_name: mmwave-sensor
 
captive_portal:

web_server:
  port: 80
  version: 2
  include_internal: true

http_request:
  useragent: esphome/$device_name
  timeout: 2s

switch:
  - platform: safe_mode
    internal: true
    name: use_safe_mode

binary_sensor:
- platform: gpio
  name: mmwave_in_bedroom
  pin:
    number: GPIO16
    mode: INPUT_PULLDOWN

uart:
  id: uart_bus
  tx_pin: GPIO4
  rx_pin: GPIO5
  baud_rate: 115200
  debug:
    direction: BOTH
    dummy_receiver: true
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

number:
  - platform: template
    name: distance
    id: distance
    min_value: 0
    max_value: 1350
    initial_value: 315
    optimistic: true
    step: 15
    restore_value: true
    unit_of_measurement: cm
    set_action:
      - uart.write: "sensorStop"
      - delay: 1s
      - uart.write: !lambda
                      int cm = (int)ceil(x / 15.0);
                      std::string cms = "detRangeCfg -1 0 " + to_string(cm);
                      return std::vector<unsigned char>(cms.begin(), cms.end());
      - delay: 1s
      - uart.write: "saveCfg 0x45670123 0xCDEF89AB 0x956128C6 0xDF54AC89"
      - delay: 1s
      - uart.write: "sensorStart"
      
  - platform: template
    name: latency
    id: latency
    min_value: 0
    max_value: 65000
    initial_value: 12500
    optimistic: true
    step: 25
    restore_value: true
    unit_of_measurement: ms
    set_action:
      - uart.write: "sensorStop"
      - delay: 1s
      - uart.write: !lambda
                      int ms = (int)ceil(x / 25.0);
                      std::string mss = "outputLatency -1 0 " + to_string(ms);
                      return std::vector<unsigned char>(mss.begin(), mss.end());
      - delay: 1s
      - uart.write: "saveCfg 0x45670123 0xCDEF89AB 0x956128C6 0xDF54AC89"
      - delay: 1s
      - uart.write: "sensorStart"   

button:
  - platform: restart
    name: Restart $device_name

  - platform: template
    name: "factory_reset_sensor"
    id: "factory_reset_sensor"
    on_press:
      - uart.write: "sensorStop"
      - delay: 1s
      - uart.write: "factoryReset 0x45670123 0xCDEF89AB 0x956128C6 0xDF54AC89"
      - delay: 3s
      - uart.write: "sensorStart"     
`

**Comment by Roellen** [comment]
I can also send you my wemos D1 mini with the mmwave sensor if you want to test/fix things.

**Comment by SimonFischer04** [comment]
I think this can be closed as it is already implemented https://github.com/DrozmotiX/ioBroker.esphome/blob/main/main.js#L378C1-L380C16 and I also just validated that it works using the given yaml.

**Comment by DutchmanNL** [comment]
> I think this can be closed as it is already implemented https://github.com/DrozmotiX/ioBroker.esphome/blob/main/main.js#L378C1-L380C16 and I also just validated that it works using the given yaml.

thank you validating :)
