### ISSUE TITLE
ESPAsyncWebServer.h: No such file or directory

### ISSUE THREAD

**Issue by marsmaennchen** [DrozmotiX/ioBroker.esphome#143]
When i try to connect to ESP32 i get the following Error:

`INFO Reading configuration /opt/iobroker/iobroker-data/esphome.0/olim1.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing olim1 (board: esp32-poe-iso; framework: arduino; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Library Manager: Installing esphome/AsyncTCP-esphome @ 1.2.2
Warning! Please upgrade to the PlatformIO Core 6
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
Warning! Please upgrade to the PlatformIO Core 6
Dependency Graph
|-- <WiFi> 1.0
|-- <FS> 1.0
|-- <Update> 1.0
|-- <DNSServer> 1.1.0
|-- <ESPmDNS> 1.0
Compiling .pioenvs/olim1/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/olim1/src/esphome/components/esp32/gpio_idf.cpp.o
Compiling .pioenvs/olim1/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/olim1/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/olim1/src/esphome/components/md5/md5.cpp.o
In file included from src/esphome/components/captive_portal/captive_portal.h:10:0,
                 from src/esphome/components/captive_portal/captive_portal.cpp:3:
src/esphome/components/web_server_base/web_server_base.h:9:31: fatal error: ESPAsyncWebServer.h: No such file or directory

***************************************************************************
* Looking for ESPAsyncWebServer.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ESPAsyncWebServer.h"
* Web  > https://registry.platformio.org/search?q=header:ESPAsyncWebServer.h
*
***************************************************************************

compilation terminated.
*** [.pioenvs/olim1/src/esphome/components/captive_portal/captive_portal.cpp.o] Error 1
========================== [FAILED] Took 7.04 seconds ==========================`

Adapter Version: 0.2.4
js-controller: 4.0.23
node Version: 16.17.1

**Comment by DutchmanNL** [comment]
Can you share the yaml please?

**Comment by marsmaennchen** [comment]
The original is:
`esphome:
  name: olim1

esp32:
  board: esp32-poe-iso
  framework:
    type: arduino


logger:


api:

ota:
  password: "9618bf39627c691246d3ac8bd014b484"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  
  ap:
    ssid: "Olim1 Fallback Hotspot"
    password: "0zpwoKiz2PbH"

captive_portal:`

And now im working on this:

`esphome:
  
  libraries: 
    esphome/ESPAsyncWebServer-esphome@^3.0.0
    ayushsharma82/AsyncElegantOTA@^2.2.7
    links2004/WebSockets@^2.3.7
  name: olim3
  
esp32:
  
  board: esp32-poe-iso
  framework:
    type: arduino


logger:


api:

ota:
  password: "e673c7fe4489af6b096051e6c4bdbb12"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

 
  ap:
    ssid: "Olim3 Fallback Hotspot"
    password: "6ZvgmMi0Xpp0"

captive_portal:`

**Comment by marsmaennchen** [comment]
Im so sorry, its very embarassing !
Seems to be my fault. With an Olimex ESP32 POE it works when i clear the lin with the WIFI parameter.
With the following Yaml it works:
`esphome:
  name: olim1

esp32:
  board: esp32-poe-iso
  framework:
    type: arduino
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

  # Optional manual IP
  manual_ip:
    static_ip: 10.110.1.22
    gateway: 10.110.1.1
    subnet: 255.255.255.0
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:`

**Comment by DutchmanNL** [comment]
please update to latest version, this is related to an outdated dependency
