### ISSUE TITLE
ESPHOME für JK BMS geht nicht.

### ISSUE THREAD

**Issue by Condor-XYZ** [DrozmotiX/ioBroker.esphome#144]
Hallo Ich habe das tolle Projekt gefunden =>  https://github.com/syssi/esphome-jk-bms
leider kommt bei Validate einige fehlermeldungen.

`INFO Reading configuration /opt/iobroker/iobroker-data/esphome.0/jk-bms.yaml...
INFO Updating https://github.com/syssi/esphome-jk-bms.git@main
ERROR Unable to import component jk_bms_ble.number:
Traceback (most recent call last):
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.7/site-packages/esphome/loader.py", line 163, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/iobroker/iobroker-data/esphome.0/.esphome/external_components/35bd8a5b/components/jk_bms_ble/number/__init__.py", line 4, in <module>
    from esphome.const import (
ImportError: cannot import name 'CONF_ENTITY_CATEGORY' from 'esphome.const' (/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.7/site-packages/esphome/const.py)
Failed config

button: [source /opt/iobroker/iobroker-data/esphome.0/jk-bms.yaml:72]
  
  Component not found: button.
  - platform: jk_bms_ble
    retrieve_settings: 
      name: jk-bms retrieve settings
    retrieve_device_info: 
      name: jk-bms retrieve device info
number.jk_bms_ble: [source /opt/iobroker/iobroker-data/esphome.0/jk-bms.yaml:79]
  
  Platform not found: 'number.jk_bms_ble'.
  platform: jk_bms_ble
  jk_bms_ble_id: bms0
  balance_trigger_voltage: 
    name: jk-bms balance trigger voltage
  cell_count: 
    name: jk-bms cell count
  total_battery_capacity: 
    name: jk-bms total battery capacity
  cell_voltage_overvoltage_protection: 
    name: jk-bms cell voltage overvoltage protection
  cell_voltage_overvoltage_recovery: 
    name: jk-bms cell voltage overvoltage recovery
  cell_voltage_undervoltage_protection: 
    name: jk-bms cell voltage undervoltage protection
  cell_voltage_undervoltage_recovery: 
    name: jk-bms cell voltage undervoltage recovery
  balance_starting_voltage: 
    name: jk-bms balance starting voltage
  voltage_calibration: 
    name: jk-bms voltage calibration
  current_calibration: 
    name: jk-bms current calibration
  power_off_voltage: 
    name: jk-bms power off voltage
  max_balance_current: 
    name: jk-bms max balance current
  max_charge_current: 
    name: jk-bms max charge current
  max_discharge_current: 
    name: jk-bms max discharge current`

Kann man den fehler irgenwie beseitigen ?

**Comment by DutchmanNL** [comment]
es wird hier eine externe Komponenten verwendet jk_bms_ble.number diese muss man separat downloaden und in den ordner /opt/iobroker/iobroker-data/esphome.0/ reinkopieren
