### ISSUE TITLE
Support of api encryption

### ISSUE THREAD

**Issue by svenerbe** [DrozmotiX/ioBroker.esphome#152]
Hi,
its planned to support api encryption (Optional): Enable transport encryption of the API layer?

The password option is Deprecated.
https://esphome.io/components/api.html
password (Optional, Deprecated, string): The password to protect the API Server with. Defaults to no password. It is recommended to use the encryption -> key above instead of the the password.

Are you working on a new release? Last update was on 2021?

**Comment by SimonFischer04** [comment]
After the library migration in https://github.com/DrozmotiX/ioBroker.esphome/pull/167 this should not be that hard to implement.

**Comment by DutchmanNL** [comment]
> After the library migration in #167 this should not be that hard to implement.

fix implemented

**Comment by SimonFischer04** [comment]
@DutchmanNL sorry to bother, where is this implemented - i can't seem to find a change? Do you only have the fix locally currently maybe?

**Comment by DutchmanNL** [comment]
> @DutchmanNL sorry to bother, where is this implemented - i can't seem to find a change? Do you only have the fix locally currently maybe?

I See I was a little to quick closing this issue

Based on your PR the new APi dependency is integrated which supports encryption, but that's only backend also need to include it in adapter logic + admin settings

Reopen

**Comment by patricknitsch** [comment]
Works perfect!

**Comment by DutchmanNL** [comment]
> Works perfect!

Lovely thank you confirming!
