### ISSUE TITLE
Bad format. Expected 0 at the begin

### ISSUE THREAD

**Issue by FranticMan** [DrozmotiX/ioBroker.esphome#155]
Beim manuellen Hinzufügen eines neuen Geräts (add device)
Die IP Adresse scheint falsch validiert zu werden.

Eingabe 192.168.178.70 -> Bad format. Expected 0 at the begin
Eingabe 0.0.0.0   -> connect ECONNREFUSED 0.0.0.0:6053

esphome v0.2.4
Node.js: v16.19.0
NPM: 8.19.3

**Comment by OstertagM** [comment]
Now I have the same problem with the automatical device detection.

**Comment by OstertagM** [comment]
Has anybody solved it? I can't add any new device and I want to go on with my programing..

**Comment by Jacke87** [comment]
bei mir genau dasselbe gibt es eine andere Möglichkeit?
Das automatische hinzufügen klappt leider gar nicht

**Comment by Matze1811** [comment]
Auch ich habe das selbe Problem,.. der Adapter ist leider nicht aktuell, sei es Number oder Button oder jetzt diese neue Fehlermeldung,.. Wird hier noch gearbeitet oder ist das Ding TOT?

**Comment by SchimmerMediaHD** [comment]
ich hänge auch am gleichen Problem, bin ja froh das ich es überhaupt geschafft habe den Adapter installiert zu bekommen, war eine ganze menge hin und her mit verschiedenen NPM und NodeJS Versionen bis alles lief und ich meine Geräte flashen konnte. Nun Funktioniert alles und in den Logs kann ich auch die Werte auslesen im ioBroker, aber bekomme die IP Adresse nicht über die Instanz hinzugefügt. Das ist irgendwie sogar noch ärgerlicher, weil man in den Logs sieht das ja irgendwie eine Verbindung zwischen dem ESP und dem ioBroker bestehen muss, weil ich die Werte von meinem Netzteil welches ich steuern möchte alle angezeigt bekomme, auch wenn ich am Gerät etwas ändere, so tauchen die Änderungen direkt in den Logs auf, heißt der ioBroker erhält ja über den espHome Adapter die Daten über die Logs rein, aber ich bekomme das "Device" leider nicht rein so das ich die Werte auch aus dem ioBroker heraus ansteuern kann. Bitte Bitte Bitte den Adapter nicht aufgeben, ich würde selbst helfen wenn ich davon etwas verstehen würde, aber bin leider auf die Community angewiesen.

**Comment by Jacke87** [comment]
Ich habe aufgegeben und einfach mqtt auf dem esp aktiviert damit funktioniert es.

**Comment by SchimmerMediaHD** [comment]
Ich habe inzwischen herausgefunden wie man die Fehlermeldung "Expected 0 at the begin" umgehen kann. Man muss in der yaml die "encryption" raus nehmen und "key" durch "password" ersetzen.

also anstatt...
```
api:
  encryption:
    key: "zgit8AZtuXUm7x4mlcOFv3lPgTLZc1tX8Y/zwergr2B="
```

muss das hier rein...
```
api:
  password: "EuerLieblingsPasswort"
```

wenn ihr das so macht könnt ihr einfach über "ADD DEVICE" die IP-Adresse von ESP eingeben und das "password", dann ist der ESP auch schon über den ESPHome Adapter im IoBroker drin.

Nachweis vor aber leider ohne "Numbers" was ich brauchte um mein Netzteil von Joy-IT smart ansteuern zu können, daher habe ich auch den MQTT Server von ioBroker in die yaml eingebunden mit...
```
# MQTT kann nur benutzt werden wenn API raus gelöscht wird (sonst startet der ESP sich alle 15 Minuten neu)
mqtt:
  broker: IP Adresse vom ioBroker 
  port: MQTT Port
  username: Beispiel
  password: EuerLieblingsPasswort
```
damit kann ich das Netzteil super steuern, als Tipp übrigens noch wenn ihr MQTT benutzt, nehmt den "api" Teil aus der yaml raus wiel der ESP sonst alle 15 Minuten neu startet.

**Comment by Jacke87** [comment]
Wie schreibst du den werte über Mqtt in IoBroker wenn ich die werte der Numbers im IoBroker im Objektbaum ändere passiert nichts?

**Comment by SchimmerMediaHD** [comment]
Über den "MQTT Adapter" von ioBroker

**Comment by Jacke87** [comment]
Bekomme ich leider nicht hin ich habe den IoBroker Adapter als Broker eingerichtet somit empfange ich die Werte vom ESPHome.
Im Blockly kann ich die den Adapter nicht auswählen. nur meine Mqtt Instanz die als Client Konfiguriert ist.
in Node Red kann ich etwas senden das kommt auch im Mqtt Explorer an allerdings nicht auf der Weboberfläche vom ESP.
In MQTT bin ich allerdings auch nicht sehr fitt

**Comment by SchimmerMediaHD** [comment]
Die MQTT Instanz in IoBroker muss ja auch als Server eingerichtet sein. Ein "Client" ist praktisch nur der Club Besucher und der "Server" ist sowas wie der Boss vom Club, der die Regeln bestimmt und sagt wer rein darf und wer nicht. Dein ESP ist ein Client, also ein Besucher, während dein ioBroker als Boss fungieren sollte. Hier schau meine Einstellung. Lass dich nicht von dem Port verunsichern welcher ein anderer MQTT Port ist als der Standard Port. (das hat bei mir seine Gründe, musst du aber nicht zwangsläufig nachmachen, nur wenn dann musst du in der yaml natürlich auch den entsprechenden Port eintragen) 
![IMG_20230624_172625](https://github.com/DrozmotiX/ioBroker.esphome/assets/39628345/b4d69f45-c7d8-4cad-89bd-07fcc22d51e6)

**Comment by Jacke87** [comment]
Habe ihn ja auch als Broker konfiguriert steht auch im ersten Satz.
Ich habe eine zweite Instanz die ist als Client konfiguriert. In blocky kann ich hier auch etwas senden.

**Comment by SchimmerMediaHD** [comment]
der MQTT Adapter hat doch auch nichts mit ESP Home zutun, ich benutze zum senden und empfangen komplett den MQTT Adapter. Den ESP Home Adapter habe ich im Grunde nur für die Firmware und die entsprechenden Einstellungen in der yaml verwendet. Die Kommunikation hat nichts mehr mit dem ESP Home Adapter zutun, da sie komplett über MQTT läuft. Im ESPHome Web Interface sowie bei dem Gerät was angesteuert wird ändern sich die Werte dementsprechend so wie ich das live im ioBroker über MQTT eingebe. Und natürlich funktioniert die Kommunikation in beide Richtungen auch die Werte vom ESP kommen über MQTT im ioBroker an, zum Beispiel der Temperatur Wert vom Sensor der den Akku kontrolliert.

eigentlich kann man da nicht viel falsch machen und wegen diesem Missverständnis, du hast gesagt das du den "ioBroker Adapter" als Broker eingerichtet hast. Es gibt keinen "ioBroker Adapter" wir reden hier über 2 Adapter. Einmal den "ESPHome Adapter" welchen ich in meinem Beispiel nur zum Einrichten der Software auf dem ESP benutze, damit dieser auch weiß was er tun soll. Dann gibt es noch den Zweiten Adapter, der "MQTT Adapter" der völlig sepperat von dem "ESPHome" Adapter ist und auch nichts mit den MQTT Einstellungen in dem ESPHome Adapter zutun hat. Dieser selbstständige "MQTT Adapter" funktioniert wenn er als Server eingerichtet ist, mit meiner yaml config die ich gepostet habe absolut einwandfrei. Wenn dem nicht so ist gibt es nur eine einzige logische Lösung.... Du machst was falsch 😅

**Comment by Jacke87** [comment]
Ich glaube wir reden aneinander vorbei. Wir habe exakt die gleiche Ausgangslage, auch ich benutze esphome nur zum erstellen der yaml und Flashen sowie Debugging übers Log.
Der Datenaustausch ist nur über denn mqtt Adapter realisiert. Ich sehe alle Datenpunkte aktuell im iobroker. Wenn ich aber nun im Objekt Baum des iobrokers etwas ändere dann steht es nur dort drin nicht in der Weboberfläche des Gerätes und auch nicht im mqqt Explorer denn ich nebenbei laufen lasse.
Wenn ich den Wert über node red publishe sehe ich den Wert im mqtt Explorer aber er wird vom esp nicht berücksichtigt, und auch nicht in der Weboberfläche geändert!

**Comment by SimonFischer04** [comment]
See: https://github.com/DrozmotiX/ioBroker.esphome/issues/152

**Comment by DutchmanNL** [comment]
solved in current new version (0.3.x)

**Comment by SimonFischer04** [comment]
I think you are little fast again with closing as completed, as this is related to the encryption support(https://github.com/DrozmotiX/ioBroker.esphome/issues/152) (that is not yet implemented?).
But can leave closed as duplicate.
