### ISSUE TITLE
Installing on iobroker -> error

### ISSUE THREAD

**Issue by Hobbyflyer** [DrozmotiX/ioBroker.esphome#163]
**Describe the bug**  
Installing in iobroker over git repo url causes error 25.
Only this Adapter. 
Debug....

ERROR: Process exited with code 25
weniger
mehr
$ iobroker url https://github.com/DrozmotiX/ioBroker.esphome --host FoxControl --debug

install DrozmotiX/ioBroker.esphome#e39b015ea803248459f5e03a7b7a775290b4ea8e

NPM version: 8.19.2

Installing DrozmotiX/ioBroker.esphome#e39b015ea803248459f5e03a7b7a775290b4ea8e... (System call)

npm ERR! code 1npm ERR! git dep preparation failednpm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/iobroker/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-runnpm ERR! > iobroker.esphome@0.2.4 installnpm ERR! > npip installnpm ERR! npm ERR! No python_modules directory; installing pip locally if needed.npm ERR! npm WARN using --force Recommended protections disabled.npm ERR! npm WARN old lockfile npm ERR! npm WARN old lockfile The package-lock.json file was created with an old version of npm,npm ERR! npm WARN old lockfile so supplemental metadata must be fetched from the registry.npm ERR! npm WARN old lockfile npm ERR! npm WARN old lockfile This is a one-time fix-up, please be patient...npm ERR! npm WARN old lockfile npm ERR! npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecatednpm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecatednpm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecatednpm ERR! npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecatednpm ERR! npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependenciesnpm ERR! Traceback (most recent call last):npm ERR! File "/home/iobroker/.npm/_cacache/tmp/git-cloneQiIQz3/node_modules/nopy/src/get-pip.py", line 20061, in <module>npm ERR! main()

host.FoxControl Cannot install DrozmotiX/ioBroker.esphome#e39b015ea803248459f5e03a7b7a775290b4ea8e: 1

ERROR: Process exited with code 25

Plattform
linux
Betriebssystem
linux
Architektur
x64
CPUs
2
Geschwindigkeit
2100 MHz
Modell
Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
RAM
4 GB
System-Betriebszeit
5 T. 02:00:15
Node.js
v16.18.1 (Es gibt eine neuere Version: v16.20.1 - Empfohlene Version v18.16.1)
time
1688667657469
timeOffset
-120
Anzahl der Adapter
479
NPM
8.19.2
Datenträgergröße
15.58 GB
freier Festplattenspeicher
11.01 GB
Betriebszeit
5 T. 02:00:13
Aktive Instanzen
38
Weg
/opt/iobroker/
Hostname
FoxControl
js controller 4.0.23

**Comment by SimonFischer04** [comment]
had the same issue. problem is probably that your used python version is not specified in `  "python": {
    "execPath": [` in `package.json`. But updating to a newer python version will most likely result in this: https://github.com/DrozmotiX/ioBroker.esphome/issues/158. I'm working on it.
