### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by Eistee82** [DrozmotiX/ioBroker.esphome#164]
![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/1881217/0a2e85b4-8841-4cdc-b56b-f2efde5d0ca9)

Adapter 0.2.4

**Comment by Eistee82** [comment]
Trying uninstall and than reinstall:
![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/1881217/9f1882bc-605f-4b09-9344-6f13a12b2912)

**Comment by Rushmed** [comment]
Hi,

I am also facing this issue.

`<html>
<body>


esphome.0 | 2023-07-25 19:09:57.341 | error | Client 192.168.178.248 not reachable !
-- | -- | -- | --
esphome.0 | 2023-07-25 19:09:41.893 | error | Client 192.168.178.254 not reachable !
esphome.0 | 2023-07-25 19:09:40.534 | warn | ESPHome Dashboard deactivated
esphome.0 | 2023-07-25 19:09:40.424 | error | [dashboardProcess ERROR] from esphome.__main__ import mainModuleNotFoundError: No module named 'esphome'
esphome.0 | 2023-07-25 19:09:40.419 | error | [dashboardProcess ERROR] Traceback (most recent call last): File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/bin/esphome", line 5, in <module>
esphome.0 | 2023-07-25 19:09:38.817 | info | Native Integration of ESPHome Dashboard enabled
esphome.0 | 2023-07-25 19:09:38.813 | info | Auto Discovery startet, new devices (or IP changes) will be detected automatically
esphome.0 | 2023-07-25 19:09:38.810 | info | Try to connect to 192.168.178.248
esphome.0 | 2023-07-25 19:09:38.799 | info | Try to connect to 192.168.178.254
esphome.0 | 2023-07-25 19:09:38.515 | info | starting. Version 0.2.4 (non-npm: DrozmotiX/ioBroker.esphome#b6adb149202b81607fe1d726bbe7ffa6717d2352) in /opt/iobroker/node_modules/iobroker.esphome, node: v18.17.0, js-controller: 4.0.24


</body>
</html>`

**Comment by SimonFischer04** [comment]
See: https://github.com/DrozmotiX/ioBroker.esphome/issues/158.
