### ISSUE TITLE
Unable to create new devices due to missing files & directories

### ISSUE THREAD

**Issue by amrap030** [DrozmotiX/ioBroker.esphome#168]
**Describe the bug**  
After installing esphome on my ioBroker instance, I got several bugs.

1. In the logs of ioBroker, I noticed failing requests to `/devices` (see 1. screenshot). The same failing requests are visible in the chrome browser when visiting the esphome dashboard. After creating a device via esphome web interface, a device is created under the objects in ioBroker, but the dashboard still doesn't show any devices. I also noticed, that there was no `esphome.0` directory created under `/opt/iobroker/iobroker-data`, maybe this is the reason, why the dashboard is empty.
2. I was only able to generate new devices via the esphome web interface, other approaches via the esphome dashboard didn't work (see 2. & 3. screenshot).
3. I see more failing requests to `/edit?configuration=secrets.yaml`, probably because there are missing `.yaml` files or directories.

**Expected behavior**  
I would expect that the adapter automatically creates necessary directories, displays newly created devices in the dashboard and all network requests are fully functioning.

**Screenshots & Logfiles**  
1.
<img width="1312" alt="Bildschirmfoto 2023-10-01 um 19 16 26" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/35061229/72571c21-7329-4fb6-927b-a9537e6c483c">

2.
<img width="405" alt="Bildschirmfoto 2023-10-01 um 19 25 58" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/35061229/a92f0a58-6251-4940-af38-ce76f329b5e7">

3.
<img width="1511" alt="Bildschirmfoto 2023-10-01 um 19 26 24" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/35061229/11f728f1-1097-48be-b79b-7df0275a6106">

**Versions:**  
 - Adapter version: 0.2.4
 - JS-Controller version: 4.0.24
 - Node version: v18.17.1
 - Operating system: docker container (buanet/iobroker:v8.1.0)

**Additional context**  
My ioBroker instance is running in a Kubernetes K3s Cluster via the Docker container. I have no idea if that is causing the problems, but I would suggest there is no difference to for example running it via standalone docker.

**Comment by Bavarialex** [comment]
Same here.
Proxmox 8 vm debian bullseye

Node.js: v18.16.0

NPM: 9.5.1
js: 5.0.12

**Comment by Bavarialex** [comment]
got it:
just manually create directory /opt/iobroker/iobroker-data/esphome.0
chown to user and owner iobroker

**Comment by DutchmanNL** [comment]
> got it:
> 
> just manually create directory /opt/iobroker/iobroker-data/esphome.0
> 
> chown to user and owner iobroker

Hmm that Directory should be automatically created, will check

**Comment by DutchmanNL** [comment]
issue found and solved, in next version adapter will automatically create this needed directory


https://github.com/DrozmotiX/ioBroker.esphome/commit/2d2ab35d6f34aed45a6a0cde4fac26a88e5c79ec#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916aR89-R101
