### ISSUE TITLE
info message from gateway

### ISSUE THREAD

**Issue by arteck** [DrozmotiX/ioBroker.esphome#175]
i have here a information that my gateway has a esp

dont know why...

![grafik](https://github.com/DrozmotiX/ioBroker.esphome/assets/6681528/8668d3c3-8065-473f-b4fd-303e9597dcb0)

https://github.com/DrozmotiX/ioBroker.esphome/blob/385216342a0b81b702149e633d26399ac88e5966/main.js#L538

**Comment by DutchmanNL** [comment]
Seems like we have a bug in autodiscovery used by the module, I will temporary disable it for now until the bug is solved

https://github.com/twocolors/esphome-native-api/issues/23

**Comment by DutchmanNL** [comment]
solved in latest git version (0.5.0-beta.10) will be part of 0.5.x release
