### ISSUE TITLE
Internes Dashboard wird nicht geöffnet

### ISSUE THREAD

**Issue by patricknitsch** [DrozmotiX/ioBroker.esphome#180]
Hi,

folgendes Problem habe ich aktuell.

das interne Dashboard wird nicht geöffnet, es wird aber auch kein Fehler angezeigt.

Folgendes zeigt das Protokoll:

<img width="1440" alt="Bildschirmfoto 2023-11-10 um 21 04 29" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/8a75409a-e1c4-478d-b025-df3525f926e7">

Über den Button möchte ich das Dashboard aufrufen. Nachfolgend wird nichts angezeigt.

![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/e4fee31c-1d22-4759-8953-41f99a58e4b6)

Ich habe dies auf meinem bestehenden Debian Container versucht(aktuellste Version) und auf einem neuen, mit frisch installiertem IoBroker und ESP Home Adapter.

Der normale Aufruf auf die IP-Adresse:6052 funktionieren aber.

Fällt dir noch etwas ein, was ich versuchen könnte?

PS: Ansonsten läuft der Adapter hervorragend!

**Comment by DutchmanNL** [comment]
> Fällt dir noch etwas ein, was ich versuchen könnte?

hast du die ip-addresse in den adapter Einstellungen hinterlegt ?

> PS: Ansonsten läuft der Adapter hervorragend!

Super, danke dir das freut mich ! Was n haufen Arbeit die letzte Woche und morgen kommt der neue admin interface :)

**Comment by patricknitsch** [comment]
Ja habe ich.

![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/54246330-33c1-4ef0-bce1-a1ee51b7843c)

Nichts anderes kann ich ja nicht einstellen?

**Comment by DutchmanNL** [comment]
> Nichts anderes kann ich ja nicht einstellen?

nein das passt so, ist das Dashboard ueber die IP Adresse:port im browser erreichbar ?

**Comment by patricknitsch** [comment]
Ja ist erreichbar. 

Ich glaube ich habe das Problem gefunden. Mein Admin ist über HTTPS erreichbar.

![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/27339838-1cd9-4af1-b4a2-8e915fc107f9)

Nach Umstellung von HTTPS auf HTTP ist das interne Dashboard auch erreichbar. 

![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/a8541734-2d58-4e4d-a998-9491caf8fa69)

Scheinbar gibt es da ein Problem.

**Comment by DutchmanNL** [comment]
Ok danke, das wäre Dan #159

**Comment by patricknitsch** [comment]
Ah das Problem ist anscheinend dann schon offen.

**Comment by DutchmanNL** [comment]
> Ah das Problem ist anscheinend dann schon offen. 

Jep, darum habe ich die beiden miteinander verlinkt.
Wie du beim anderen siehst muss da ne Abhängigkeit geklärt werden

**Comment by DutchmanNL** [comment]
ich schliss hier mal da wir #159 zur Behebung haben, als workarround leider nur ohne https moeglich

https://github.com/DrozmotiX/ioBroker.esphome/commit/a04a200486a21b651f535097cadfda0c6a9eab37
