### ISSUE TITLE
[deviceDiscovery handler] TypeError: Cannot read properties of undefined (reading 'connectError')

### ISSUE THREAD

**Issue by arteck** [DrozmotiX/ioBroker.esphome#181]
in version 0.4.1
![grafik](https://github.com/DrozmotiX/ioBroker.esphome/assets/6681528/8e402d05-2109-46b7-9f16-d553d80d8ade)

**Comment by DutchmanNL** [comment]
> in version 0.4.1
> 
> ![grafik](https://github.com/DrozmotiX/ioBroker.esphome/assets/6681528/8e402d05-2109-46b7-9f16-d553d80d8ade)
> 
> 

Thank you, solved in Branche will make a new release today incl new admin interface
