### ISSUE TITLE
Instanz wird bei Installation nicht angelegt und Admin Tab wird nicht angezeigt

### ISSUE THREAD

**Issue by Protheus23** [DrozmotiX/ioBroker.esphome#187]
Hi,

ich habe jetzt den Adapter in Version 4.1 Installiert und vorher in 5.0.1 Beta.

Bei beiden Installationen wird aber keine Instanz angelegt. (Bin ich zu doof zum installieren?)
Im Admin wird aber auch kein esphome Tab angelegt.

Infos zum System:
iobroker im Docker
Plattform: docker (official image - v9.0.1)
NPM: 9.8.1
Node.js: v18.18.2

Evtl. kann ja wer den entscheidenden Tip geben :)

**Comment by DutchmanNL** [comment]
> Bei beiden Installationen wird aber keine Instanz angelegt. (Bin ich zu doof zum installieren?)

garantiert nicht, eventuell machst du nur die falschen schritte :)
Wie installierst du ihn, über den admin oder aus git ?

Bei git Installationen z.b muss man immer selber die Instanz erstellen beim adapter, macht man die installation aus dem admin wird automatisch eine erstellt.
( ich rate auch von Installationen aus git ab, da hier manchmal noch versionen/code liegen die noch nicht reif zur installation sind

Es koennte auch sein das die Installation fehl schlägt, das sollte aber dan im log sichtbar sein

**Comment by Protheus23** [comment]
> > garantiert nicht, eventuell machst du nur die falschen schritte :) Wie installierst du ihn, über den admin oder aus git ?
> 
Im Admin taucht der als Adapter nichtmal auf :)
<img width="724" alt="image" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/60545975/fbe782cb-1247-4ceb-9dd1-af5de6462aa1">

Daher per Github-URL...

> Bei git Installationen z.b muss man immer selber die Instanz erstellen beim adapter, macht man die installation aus dem admin wird automatisch eine erstellt. ( ich rate auch von Installationen aus git ab, da hier manchmal noch versionen/code liegen die noch nicht reif zur installation sind
> 
Wenn ich das Paket per Github installiert habe (Instanz taucht halt nicht auf) Tuacht das Paket auch als Adapter-Möglichkeit auf aber eine Instanz wird nicht erstellt.
Wie macht man das manuell?

> Es koennte auch sein das die Installation fehl schlägt, das sollte aber dan im log sichtbar sein
>
Ein Fehler war nicht aufgetreten

**Comment by patricknitsch** [comment]
Der Adapter ist nur in der beta repo zu sehen, da es noch keine stable Version gibt. Schalte auf beta um, dann findest du die aktuelle Version

**Comment by DutchmanNL** [comment]
> Super!
> 
> Die Installation klappte nun schonmal 😄 
> 
> 
> 
> Allerdings funktioniert dies nicht, bzw. kann nicht geöffnet werden.
> 
> Ich bekomme auch den folgenden Fehler:
> 
> <img width="738" alt="image" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/60545975/db6364e7-aa1a-4139-b229-39c1d94547da">
> 
> 

Hast du die 0.5.1 installiert ?
Der Fehler sagt im Grunde das er einen Ordner nicht finden kan den der Adapter automatisch erstellen sollte

Was für ein System ist es, linux/docker/windows ?

**Comment by SimonFischer04** [comment]
> Daher per Github-URL...

![Screenshot_20231114-232102_1_1.png](https://github.com/DrozmotiX/ioBroker.esphome/assets/20473239/35e2fdda-5268-4dfe-9dac-46b820a9f455)

Sorry, aber manchmal würds helfen zumindest das zu lesen wo man url eingibt ... :)

**Comment by SimonFischer04** [comment]
> Super!
> Die Installation klappte nun schonmal 😄 
> 
> Allerdings funktioniert dies nicht, bzw. kann nicht geöffnet werden.
> Ich bekomme auch den folgenden Fehler:
> <img width="738" alt="image" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/60545975/db6364e7-aa1a-4139-b229-39c1d94547da">
> 

Gibts im normalen iobroker log nen genaueren fehler welche file / directory fehlt?

**Comment by DutchmanNL** [comment]
@Protheus23 

Siehst du beim starten des Adapter die Meldung 

"ESPHome directory created"

Oder

"`ESPHome DDashboard is unable to access directory to store YAML configuration data, please run ioBroker fix"?

Wen die letztere, mal ioBroker Fix ausgeführt um eventuelle Berechnungs Fehler zu beheben 

@SimonFischer04 

Eigentlich solltet dieser Teil derartige Fehler abfangen 

https://github.com/DrozmotiX/ioBroker.esphome/blob/main/main.js#L122C8-L122C8

**Comment by SimonFischer04** [comment]
Ja drum hab ich nach log gefragt was fehlt, könnt auch sein das die python/esphome binary directory fehlt

**Comment by SimonFischer04** [comment]
Glaub setzt mich dann echt bald mal an issue template mit yaml und log-eintrag... 
:)

**Comment by Protheus23** [comment]
> @Protheus23
> 
> Siehst du beim starten des Adapter die Meldung
> 
> "ESPHome directory created"
> 
> Oder
> 
> "`ESPHome DDashboard is unable to access directory to store YAML configuration data, please run ioBroker fix"?
> 
> Wen die letztere, mal ioBroker Fix ausgeführt um eventuelle Berechnungs Fehler zu beheben
> 
> @SimonFischer04
> 
> Eigentlich solltet dieser Teil derartige Fehler abfangen
> 
> https://github.com/DrozmotiX/ioBroker.esphome/blob/main/main.js#L122C8-L122C8

@DutchmanNL 

nein, taucht da nicht auf

<img width="865" alt="image" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/60545975/efd5da3c-3aad-4bda-95f7-21fd68877996">

Bei Docker ist der iobroker-fix ja scheinbar Bestandteil des Startscripts und neu gestartet hatte ich ja auch.

@SimonFischer04 
Ja ist die 5.0.1 Beta.

**Comment by DutchmanNL** [comment]
> Bei Docker ist der iobroker-fix ja scheinbar Bestandteil des Startscripts und neu gestartet hatte ich ja auch.

korrekt, auf was fuer einem system läuft deine docker installation?

**Comment by Protheus23** [comment]
Unraid Server (basiert wohl auf Slackware)

**Comment by DutchmanNL** [comment]
> Unraid Server (basiert wohl auf Slackware)

ich tappe momentan ehrlich gesagt im dunklen da der Fehler auch nicht aussage kräftig ist :/
der port (6052) ist nicht zuefallig belegt ?

**Comment by Protheus23** [comment]
> > Unraid Server (basiert wohl auf Slackware)
> 
> ich tappe momentan ehrlich gesagt im dunklen da der Fehler auch nicht aussage kräftig ist :/ der port (6052) ist nicht zuefallig belegt ?

Ich würde sagen, nein (Aber ich stecke jetzt auch nicht wirklich tief in Linux drin)

<img width="819" alt="image" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/60545975/5c1a7115-82dc-4282-a12d-2d5b37c73ecf">

**Comment by Protheus23** [comment]
Ich habe jetzt den Adapter nochmal deinstalliert, die Zugriffsberechtigungen auf den Storage geprüft und den Adapter neu installiert:

`$ iobroker add esphome auto --host automat01.iot.schauthe.local --debug
NPM version: 9.8.1Installing iobroker.esphome@0.5.0-beta.1... (System call)
156 packages are looking for funding run `npm fund` for details
host.automat01.iot.schauthe.local install adapter esphome
upload [21] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/admin.d.ts admin.d.ts video/mp2t
upload [20] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/esphome.png esphome.png image/png
upload [19] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/i18n/de/translations.json i18n/de/translations.json application/json
upload [18] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/i18n/dum/translations.json i18n/dum/translations.json application/json
upload [17] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/i18n/en/translations.json i18n/en/translations.json application/json
upload [16] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/i18n/es/translations.json i18n/es/translations.json application/json
upload [15] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
upload [14] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/i18n/it/translations.json i18n/it/translations.json application/json
upload [13] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
upload [12] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
upload [11] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
upload [10] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
upload [9] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
upload [8] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/img/connectionError.png img/connectionError.png image/png
upload [7] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/img/connectionOK.png img/connectionOK.png image/png
upload [6] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/img/dashboard.png img/dashboard.png image/png
upload [5] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/img/deviceTabEmpty.png img/deviceTabEmpty.png image/png
upload [4] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/img/deviceTree.png img/deviceTree.png image/png
upload [3] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/index_m.html index_m.html text/html
upload [1] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/style.css style.css text/css
upload [0] esphome.admin /opt/iobroker/node_modules/iobroker.esphome/admin/words.js words.js application/javascript
host.automat01.iot.schauthe.local object system.adapter.esphome created/updated
host.automat01.iot.schauthe.local create instance esphome
host.automat01.iot.schauthe.local object system.adapter.esphome.0.alive created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.connected created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.compactMode created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.cpu created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.cputime created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.memHeapUsed created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.memHeapTotal created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.memRss created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.uptime created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.inputCount created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.outputCount created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.eventLoopLag created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.sigKill created
host.automat01.iot.schauthe.local object system.adapter.esphome.0.logLevel created
host.automat01.iot.schauthe.local object esphome.0.info created
host.automat01.iot.schauthe.local object esphome.0.info.connection created
host.automat01.iot.schauthe.local Set default value of esphome.0.info.connection: false
host.automat01.iot.schauthe.local object system.adapter.esphome.0 created
Process exited with code 0`

Da sind keine Fehler aufgetreten.
Aber nach dem Speichern der Instanzeinstellungen, kommt wieder der Nonexistingfileerror.

**Comment by DutchmanNL** [comment]
> Ich würde sagen, nein (Aber ich stecke jetzt auch nicht wirklich tief in Linux drin)

passt ich sehe keinen belegten port

> Aber nach dem Speichern der Instanzeinstellungen, kommt wieder der Nonexistingfileerror.

Habe mal einen neue docker aufgesetzt um das zu reproduzieren, ohne erfolg das dashboard und der process funktionieren :/

![Screenshot 2023-11-15 at 12 05 33](https://github.com/DrozmotiX/ioBroker.esphome/assets/7318445/e0bc3951-4ceb-447f-b7d3-60d93bd9a408)

**Comment by DutchmanNL** [comment]
@Protheus23 

könntest du mal bitte schauen über die console op dieser Ordner da ist ?

/opt/iobroker/iobroker-data/esphome.0/

am einfachste mit

```
ls -l /opt/iobroker/iobroker-data/
```

**Comment by Protheus23** [comment]
> @Protheus23
> 
> könntest du mal bitte schauen über die console op dieser Ordner da ist ?
> 
> /opt/iobroker/iobroker-data/esphome.0/
> 
> am einfachste mit
> 
> ```
> ls -l /opt/iobroker/iobroker-data/
> ```

Ja, ist da

<img width="498" alt="image" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/60545975/0790f524-83c7-450b-8c8f-f2a9a5ed88d4">

Allerdings leer. Muss das so?

**Comment by SimonFischer04** [comment]
> > @Protheus23
> > Siehst du beim starten des Adapter die Meldung
> > "ESPHome directory created"
> > Oder
> > "`ESPHome DDashboard is unable to access directory to store YAML configuration data, please run ioBroker fix"?
> > Wen die letztere, mal ioBroker Fix ausgeführt um eventuelle Berechnungs Fehler zu beheben
> > @SimonFischer04
> > Eigentlich solltet dieser Teil derartige Fehler abfangen
> > https://github.com/DrozmotiX/ioBroker.esphome/blob/main/main.js#L122C8-L122C8
> 
> @DutchmanNL
> 
> nein, taucht da nicht auf
> 
> <img alt="image" width="865" src="https://user-images.githubusercontent.com/60545975/283068260-efd5da3c-3aad-4bda-95f7-21fd68877996.png">
> Bei Docker ist der iobroker-fix ja scheinbar Bestandteil des Startscripts und neu gestartet hatte ich ja auch.
> 
> @SimonFischer04 Ja ist die 5.0.1 Beta.

aus dem log werd ich leider auch nd wirklich schlau. schau mal pls auch mal obs diese directory gibt:
`ls -la ~/.cache/autopy/venv/esphome/`

**Comment by SimonFischer04** [comment]
> Ich habe gerade mal im Filesystem geschaut...Am "Sonderzeichen" im Pfad kanns aber nicht liegen oder?

nein in js/npm sind @ zeichen ein feature

**Comment by SimonFischer04** [comment]
> Aber nach dem Speichern der Instanzeinstellungen, kommt wieder der Nonexistingfileerror.

aber erst sobald du das integrierte dashboard aktivierst? vorher gehts noch ohne fehler?

**Comment by SimonFischer04** [comment]
> Allerdings leer. Muss das so?

vielleicht. bei mir sieht er so aus:
![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/20473239/04b4116e-b1f5-49a0-a01b-de503ddacb3e)

die yamls hast in ner leeren installation naürlichnoch nicht, aber weiß nd ob er den .esphome folder schon vorher anlegen soll oda auch erst wenn man das erste mal was compiliert

**Comment by Protheus23** [comment]
> > Aber nach dem Speichern der Instanzeinstellungen, kommt wieder der Nonexistingfileerror.
> 
> aber erst sobald du das integrierte dashboard aktivierst? vorher gehts noch ohne fehler?

Ja, der Fehler taucht nicht auf.
Aber die Seite ESPhome Seite ist auch nicht erreichbar.

Da ich aber schon länger meinen iobroker auf ein anderes System (Docker auf Debian 12) umziehen wollte mache ich dies halt jetzt.
Ich gebe dann Rückmeldung obs damit geht.

**Comment by Protheus23** [comment]
Hm...äußerst spannend 😄 

<img width="583" alt="image" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/60545975/5f97ebea-351c-4ec4-b340-48d734cd5c41">

Wenn ich die URL nun direkt eingebe geht es. (http)
Über Admin allerdings nicht (https)

Würde mir so aber auch schon reichen.
Danke an alle 👍

**Comment by DutchmanNL** [comment]
> Über Admin allerdings nicht (https)
> 
> Würde mir so aber auch schon reichen.
> Danke an alle 👍

Das ist leider bereits bekannt und wird auch dran gearbeitet, habe dafür aber eine externe Abhängigkeit siehe #180 und #159

Ich mach hier Dan mal zu 👌

**Comment by SimonFischer04** [comment]
So oft wie das jetzt schon aufkam, sollt ma villeicht dazu auch noch was ind readme schreiben. @DutchmanNL hab grad auch gesehen du hast da schon einige changes gemacht mit dem neuen stuff wie encryption,... 
 👍

**Comment by DutchmanNL** [comment]
> So oft wie das jetzt schon aufkam, sollt ma villeicht dazu auch noch was ind readme schreiben. @DutchmanNL hab grad auch gesehen du hast da schon einige changes gemacht mit dem neuen stuff wie encryption,... 👍

fair point : https://github.com/DrozmotiX/ioBroker.esphome/commit/a04a200486a21b651f535097cadfda0c6a9eab37
