### ISSUE TITLE
Geräte werden als offline angezeigt, Device Error nach Neustart Adapter

### ISSUE THREAD

**Issue by patricknitsch** [DrozmotiX/ioBroker.esphome#189]
Hi,

ich habe heute die Beta version 5.1 getestet. Grundsätzlich konnte ich alle Geräte mittels Api verbinden. 

![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/fa9d8d2d-09c3-49dc-8270-c92e46d9f4ae)

Nach Neustart des Adapters habe ich aber folgende Fehlermeldungen erhalten. Die Fehlermeldungen sind nur einmal aufgetreten.

<img width="1440" alt="5f9JK" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/841e8e36-c1c3-4a35-8d1b-28e4e122c587">

Außerdem ist mir aufgefallen, dass die Geräte zwar connected anzeigen, aber bei Offline steht false. Auch werden die geänderten Werte nicht an die Geräte übertragen.

<img width="1440" alt="Bildschirmfoto 2023-11-14 um 19 49 59" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/c7fd0621-2756-4b38-8dd7-6fe72099e2b5">

Der Adapter denkt nach öffnen der Instanzeinstellungen jedes mal, es wurde eine Änderung durchgeführt.

**Comment by patricknitsch** [comment]
Kleiner Nachtrag: 

Wenn ich die Geräte verbinde, die Einstellungen im Adapter aber nicht übernehme und er somit nicht neu startet, sind alle Geräte verbunden und können bedient werden. Sobald der Adapter neu gestartet wird, sind die Geräte nicht mehr online und können nicht mehr bedient werden

**Comment by DutchmanNL** [comment]
> Kleiner Nachtrag: 
> 
> 
> 
> Wenn ich die Geräte verbinde, die Einstellungen im Adapter aber nicht übernehme und er somit nicht neu startet, sind alle Geräte verbunden und können bedient werden. Sobald der Adapter neu gestartet wird, sind die Geräte nicht mehr online und können nicht mehr bedient werden

Danke, ich kam das bei mir nicht reproduzieren aber merke das einige wohl dieses Problem haben

Währe es möglich mal zusammen bei dir drüber zu schauen damit ich verstehe was da passiert, es reproduzieren und lösen kan ?

**Comment by patricknitsch** [comment]
Ja natürlich. Sag mir, wie ich dich unterstützen kann

**Comment by DutchmanNL** [comment]
> Ja natürlich. Sag mir, wie ich dich unterstützen kann

am einfachste waehre sich im discord zu treffen :)

**Comment by patricknitsch** [comment]
Hab dir ne Anfrage geschickt

**Comment by DutchmanNL** [comment]
> Hab dir ne Anfrage geschickt

hmm habe keine bekommen ? habe beta.2 gerade hochgeladen bitte mal probieren (über git installieren)

**Comment by patricknitsch** [comment]
Beta habe ich getestet. Die Geräte bleiben jetzt alle online. Ich erhalte aber für einige Geräte jetzt folgende Fehlermeldungen:

![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/87355fac-9dca-44f5-a4a1-b2cc64e6659b)

Diese Objekte fehlen jetzt anscheinend und werden nicht mehr angelegt.

Unter welchem Namen Bist du in Discord? DutchmanNL ?

**Comment by DutchmanNL** [comment]
> Beta habe ich getestet. Die Geräte bleiben jetzt alle online. Ich erhalte aber für einige Geräte jetzt folgende Fehlermeldungen:
> 
> ![image](https://user-images.githubusercontent.com/114565561/283219783-87355fac-9dca-44f5-a4a1-b2cc64e6659b.png)
> 
> Diese Objekte fehlen jetzt anscheinend und werden nicht mehr angelegt.
> 
> Unter welchem Namen Bist du in Discord? DutchmanNL ?

<img width="323" alt="Screenshot 2023-11-15 at 22 10 24" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/7318445/7b9e4d2f-8331-4503-87fb-566e0edf1913">
