### ISSUE TITLE
Gerät kann nicht hinzugefügt werden

### ISSUE THREAD

**Issue by patricknitsch** [DrozmotiX/ioBroker.esphome#198]
Hi Dutchman,

ich habe ein Gerät im Adapter, bei dem die Mac Adresse falsch angezeigt werden. 

![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/f757fcdb-0d01-4fa2-9e1d-5a649cbcfa47)

Möchte ich das Gerät hinzufügen, erscheint folgende Fehlermeldung:

![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/77ec0951-e3a7-42e8-8794-51f0aae91e87)

Ich kann das Gerät aber auch nicht löschen. Das Interface reagiert nicht.

Die Mac wird in ESP Home richtig angezeigt.

![image](https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/5a723322-6652-4559-a5af-cad84daf82b6)

Hast du eine Idee, woran das liegen könnte?

**Comment by patricknitsch** [comment]
Siehst du eine Möglichkeit @DutchmanNL ?

**Comment by patricknitsch** [comment]
Hi Dutchman,

das Problem besteht aktuell auch noch bei mir. Es ist mir nicht möglich, das Gerät hinzuzufügen. Die MAC Adresse wird falsch angezeigt. Wird aber von ESP Home richtig übergeben.

<img width="1089" alt="image" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/887dde05-46a7-4b8a-ab74-b277ea15e77f">

<img width="651" alt="image" src="https://github.com/DrozmotiX/ioBroker.esphome/assets/114565561/708ba5be-a7fa-4daf-adad-a38077c9d51f">

**Comment by SimonFischer04** [comment]
Werd mich (hoffentlich) demnächst mal wieder dem Adapter widmen, mal schauen ob ich was herausfinden kann.

**Comment by SimonFischer04** [comment]
@patricknitsch 

Kann das Problem leider nicht reproduzieren. Eventuell ein Problem mit discovery.
Schonmal probiert Gerät zum Löschen und über manuelle IP-Eingabe wieder hinzuzufügen?

> Ich kann das Gerät aber auch nicht löschen. Das Interface reagiert nicht.

Kannst auch probieren einfach mal das Device Objekt incl. childs zum Löschen und dann Adapter neustarten.

![image](https://github.com/user-attachments/assets/af50f9d8-7929-424b-972c-814d8f9c1f6a)

**Comment by patricknitsch** [comment]
Ich habe vorhin nochmals versucht, das Gerät manuell über die IP Adresse hinzuzufügen. Aktuell gibt es auch ein Discovery Update(zwar noch Beta), habe ich aber mal aktualisiert. Gerade eben konnte ich das Gerät auch wieder hinzufügen. Ob es jetzt letztendlich mit dem Update zusammenhing, möchte ich erstmal nicht sagen.

Immerhin funktioniert es jetzt erstmal wieder.

Danke für deine Unterstützung!

**Comment by SimonFischer04** [comment]
> Aktuell gibt es auch ein Discovery Update

Esphome wird noch nicht vom Discovery Adapter unterstützt, sollte kein Zusammenhang bestehen.
