### ISSUE TITLE
device is offline in 0.5.0-beta.10

### ISSUE THREAD

**Issue by arteck** [DrozmotiX/ioBroker.esphome#208]
diesen Fehler hatten wir schon mal

![grafik](https://github.com/DrozmotiX/ioBroker.esphome/assets/6681528/55c78d7d-0b1a-44fb-b660-a6bce762dd90)

device ist online und steuerbar leider nicht über dashboard editierbar

![grafik](https://github.com/DrozmotiX/ioBroker.esphome/assets/6681528/6bc4d165-9ce6-4c75-a12c-3a713e201c41)

der esp ist im anderen Netz.. als die iobroker instanz

**Comment by SimonFischer04** [comment]
Im Adapter ist er online, da dieser direkt per IP zugreift.

Dashboard versucht domain garage.local aufzulösen. Damit das auch Netzübergreifend funktioniert ist ein mDNS proxy / forwarder oder ähnliches nötig.

**Comment by arteck** [comment]
ich hab gefunden ..dachte zuerst auch an mDNS aber nope
`
name_add_mac_suffix: false
`
ist es.. steht der auf true kann er das gerąt nicht auflösen

**Comment by SimonFischer04** [comment]
Spannend,
ich hat das gleiche mal mit mDNS.
Aber ok, tolll dast du eine Lösung gefunden hast.
👍
