### ISSUE TITLE
Set Entity ID

### ISSUE THREAD

**Issue by crosenbe** [DrozmotiX/ioBroker.esphome#222]
I didn't find any way to specify the entity ID. I assume the ID is generated in ESPhome and used to create the name of the object. Did i miss the possibility to setup the name of the sensor in esphome? Is there any available solution to define the entity ID in esphome or in ioBroker?

**Comment by DutchmanNL** [comment]
You can Always choose a name, See the examples for that

Id is generated esp itself so no possibility to set/change :)

**Comment by crosenbe** [comment]
Thanks a lot!
