### ISSUE TITLE
Request for integration - ESPHome Light Component - state for transitionLength

### ISSUE THREAD

**Issue by bigd-73** [DrozmotiX/ioBroker.esphome#32]
Hello Dutchman,

i saw that the state "transitionLength" is specified under "async lightCommandService" in the Nafaya API. Is it possible to integrate this state?

Here is an example with the equivalent in the mqtt string.
`{"effect":"None","state":"OFF","brightness":150,"transition":2,"color":{"r":0,"g":0,"b":0},"white_value":255}`

Regards Mario

**Comment by DutchmanNL** [comment]
I did take a look at it, the value is not provided by the JSON input so I will manually hard-code create it for light states in one of the new releases

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.esphome/releases/tag/v0.2.1-1
https://github.com/DrozmotiX/ioBroker.esphome/commit/f5e382818034c98177e6fe1d9f4767befcc98ad9
