### ISSUE TITLE
Deleting not existing datapoints

### ISSUE THREAD

**Issue by FredF63** [DrozmotiX/ioBroker.esphome#39]
The adapter should delete not anymore existing datapoints, like from changing name of sensors.
Today the old sensor datapoint is still existing.
[https://forum.iobroker.net/topic/42741/esphome-beta-release/103](url)

**Comment by DutchmanNL** [comment]
Thanks will implement it during one of the next versions.

**Comment by SimonFischer04** [comment]
I think this can be closed, as it is already implemented: https://github.com/DrozmotiX/ioBroker.esphome/blob/main/main.js#L340C7-L350C8

**Comment by SimonFischer04** [comment]
Hi durch meine Änderungen mit testen von anderen configs / implementieren und fixen bin ich hierauf gestoßen - hab mittlerweile einige Sensoren Überreste (ja manuell löschen geht, aber das ja langweilig xD).

@DutchmanNL seh im verlinkten Forum-Beitrag einen kommentar von dir "Der Adapter löscht keine states, könnte man einbauen wen gewünscht habe dafür auch Code von anderen Adaptern". Sind die Public / welche - please link.

Wie wäre das Löschen angedacht? Gibts nenn Weg alle aktiven entities von nem device zu bekommen von esphome? ` on('deviceInfo'` kommen nur generallle device-daten und `.on('newEntity'` ist immer nur 1 devices.
Andere Möglichkeit wär natürlich einfach beim connect eines devices vorher alle iobroker datenpunkte zu löschen - da der initiale state ja eh abgefragt wird und somit würden sie ja eh sofort wieder erstellt werden?

**Comment by DutchmanNL** [comment]
> Wie wäre das Löschen angedacht? Gibts nenn Weg alle aktiven entities von nem device zu bekommen von esphome? ` on('deviceInfo'` kommen nur generallle device-daten und `.on('newEntity'` ist immer nur 1 devices.
> Andere Möglichkeit wär natürlich einfach beim connect eines devices vorher alle iobroker datenpunkte zu löschen - da der initiale state ja eh abgefragt wird und somit würden sie ja eh sofort wieder erstellt werden?

Danke fürs mitdenken ! :)

Ich habe beispiel code von closed source projecten, stelle ich aber gerne fuer die commune bereit wir muessen es nur den gegebenheiten anpassen :)

Da die daten struktur aufgebaut ist als Device.type.state (device/channel/state) wuerde ich 3 varianten vorschlagen.
Basis ist das der adapter alle erstellten objecten zwischen speichert, damit wir er auch immer alle object aufraumen von geraeten die er nach einem neustart nicht kennt.
Um das ab zu fangen ist denke ich mal volgende reihenfolge sinnvol

- Das loeschen von devices (recursive)
  - sollte nich automatisch passieren, den es sind nicht immer alle devices bei einem adapter neustart online
  - koennte per button unter info eingebunden werden
  - die function loescht dan alle geraete die in dem moment nicht online/verbunden sind
  - object recursive loeschen, damit sind direct alle unterliegenden objekte weck was uns bei den naesten schritt rechen kapazitaet spart

- Das loeschen channel (recursive)
  - wen sich eine device verbindet, sollte diese und deren objekte zwischen gespeichert werden https://github.com/DrozmotiX/ioBroker.esphome/blob/main/main.js#L248
  - ers sollte diese (siehe code beipsiel) ein eperates object pro geraet erstellt werden mit darunter den channel/states und diese bei einem reconnect erst loechen und dan (vorger eintrag) neu srchreiben
  - nachdem die device komplett ausgelesen ist, wird die funktion "channel cleanup" ausgefuert, alle unnoteigen channel und damit auch unterliegen states verschwinden

- Das loeschen states
  - wir ausgefuehrt nachdem alle channel aufgeraeumt sind
  - als letzteres durchlaufen wir alle states die uebrig sind und schmeissen weck was unnoetig ist

so zum code beispiel:

speicher reservieren fuer unsere objecte, zb im constructor

```
		// Memory spaces for definitions & device configuration
		this.createdObjects = {
			'devices' : [],
			'channel' : [],
			'states' : []
		}; // All created adapter object

```

Dan immer wen wir ein object erstellen, dieses auch in die array schreiben. dabei muss man aufappsen das mane es in die richtige object array schreibt (devices/channel/states)
Da wir bei diesem adapter adapter aenderungen im laufenden betreib haben koennen, sollten wir noch unter channel undstates eine array fuer das jeweilige geraet erstellen.

```
			// Create device channel
			// @ts-ignore
			if (!this.createdObjects.channel.includes(`devices`)) {
				await this.extendObjectAsync(`devices`, {
					type: 'channel',
					common: {
						name: `All devices`,
					},
					native: {},
				});
				// @ts-ignore
				this.createdObjects.channel.push(`${this.namespace}.devices`);
			}
```

Nur hier sollte halt pro geraet noch ein seperates object sein

```
this.createdObjects.channel[DEVICE].push(`${this.namespace}.devices`);
```

und diese bei einem reconnect erst komplett leren und dan neu aufbauen



> Andere Möglichkeit wär natürlich einfach beim connect eines devices vorher alle iobroker datenpunkte zu löschen - da der initiale state ja eh abgefragt wird und somit würden sie ja eh sofort wieder erstellt werden?

da wir jetzt alle werte im arbeitspeicher haben, koennen wir diese sehr gezielt loeschen.
Ich habe hier beispiel code von einer function die alle devices/channel/states mit objectView abruft und unnoetige loescht.

Diese muesste man seperatieren in devices (fuers aufraumen aller geraete die offline sind) und channel/states.
Zudem die verschachtlung mit dem geraete object implementieren

Hoffe der code ist ein bissl verstaendlich :)

- alle objecte auslesen (object view)
- diese mit denem im speicher vergleichen
- fuer nicht existierende einen console.log ausgeben und loeschen

```angular2html

	/**
	 * Cleanup objects & states not created by adapter
	 */
	async objectCleanup(){
		try {

			// Set parameters for object view to only include objects within adapter namespace
			const params = {
				startkey : `${this.namespace}.`,
				endkey : `${this.namespace}.\u9999`,
			};

			// Get all current channels
			const _channels = await this.getObjectViewAsync('system', 'channel', params);
			// List all found channels & compare with memory, delete unneeded channels
			for (const currDevice in _channels.rows) {
				// @ts-ignore
				if (!this.createdObjects.channel.includes(`${_channels.rows[currDevice].id}` )
					&& _channels.rows[currDevice].id !== `${this.namespace}.info`){
					console.log(`Unknown Channel found, delete ${_channels.rows[currDevice].id}`);
					await this.delObjectAsync(_channels.rows[currDevice].id, {recursive: true});
				}
			}

			// Get all current devices in adapter tree
			const _devices = await this.getObjectViewAsync('system', 'device', params);
			// List all found devices & compare with memory, delete unneeded devices
			for (const currDevice in _devices.rows) {
				// @ts-ignore
				if (!this.createdObjects.devices.includes(`${_devices.rows[currDevice].id}`)){
					console.log(`Unknown Device found, delete ${_devices.rows[currDevice].id}`);
					await this.delObjectAsync(_devices.rows[currDevice].id, {recursive: true});
				}
			}

			// Get all current states in adapter tree
			const _states = await this.getObjectViewAsync('system', 'state', params);
			// List all found states & compare with memory, delete unneeded states
			for (const currDevice in _states.rows) {
				// @ts-ignore
				if (!this.createdObjects.states.includes(`${_states.rows[currDevice].id}`)
					&& _states.rows[currDevice].id.split('.')[2] !== 'info'){
					console.log(`Unknown State found, delete ${_states.rows[currDevice].id}`);
					await this.delObjectAsync(_states.rows[currDevice].id);
				}
			}

		} catch (e) {
			this.log.error(`[objectCleanup] Fatal error ${e} | ${e.stack}`);
		}
	}
}

```

**Comment by SimonFischer04** [comment]
> da wir jetzt alle werte im arbeitspeicher haben, koennen wir diese sehr gezielt loeschen.
Ist natürlich die saubererer Variante.

Zu all den `createdObjects` Sachen. Passiert das speichern nicht bereits in `this.deviceInfo` https://github.com/DrozmotiX/ioBroker.esphome/blob/main/main.js#L35. Ja bezieht sich auf die esphome Daten und nicht speziell die Iobroker Datenpunkte, aber die ioBroker Objects werden ja daraus erstellt / sollten sich auch später daraus wieder ableiten lassen zum vergleichen. Spart das (doppelte?) und möglicherweise inkonsistente Speichern von espdaten <-> iobroker objects.

**Comment by SimonFischer04** [comment]
> wen sich eine device verbindet, sollte diese und deren objekte zwischen gespeichert werden https://github.com/DrozmotiX/ioBroker.esphome/blob/main/main.js#L248
> * nachdem die device komplett ausgelesen ist

genau das war meine initiale Überlegung. Woher wissen wir dass das Gerät komplett ausgelesen ist?. Beim ` .on('deviceInfo',` kommen ja nur generelle Device-Daten und `.on('newEntity'` kommen dann in undefiniertem intervall EINZELN die Channels/States z.B. 1mal type: Button, 1mail type Select, ... => wie wissen wenn alle da sind?

**Comment by DutchmanNL** [comment]
> > wen sich eine device verbindet, sollte diese und deren objekte zwischen gespeichert werden https://github.com/DrozmotiX/ioBroker.esphome/blob/main/main.js#L248
> 
> > * nachdem die device komplett ausgelesen ist
> 
> 
> 
> genau das war meine initiale Überlegung. Woher wissen wir dass das Gerät komplett ausgelesen ist?. Beim ` .on('deviceInfo',` kommen ja nur generelle Device-Daten und `.on('newEntity'` kommen dann in undefiniertem intervall EINZELN die Channels/States z.B. 1mal type: Button, 1mail type Select, ... => wie wissen wenn alle da sind?

Ich schaue es mir im laufe des Mittags/abends mal an bezüglich den Entitäten und werde erstmal cleanup für devices implementieren

Den Rest kann man Dan danach machen anhand der Struktur

Gute remark btw bezüglich des anderen entity cache im code der sollte bei reconnect auch aufgeräumt und neu gebaut werden

Ich muss noch ne abzugsanlage bauen mit esphome Control kam ich direkt auch bissl schauen wie es sich verhält

**Comment by DutchmanNL** [comment]
@SimonFischer04 ich habe in der jetzigen version (0.3.2) die basis dafter gemacht die weiter implementieren zu können, als nächstes kommt dan das löschen der Geräte danach können wir uns um states und channel kümmern.


Dein Ansatz/remark mit der deviceInfo war sehr gut, ab version 0.3.2 wird beim einem disconnect/connect de Speicher fuer die device jetzt komplett neu aufgebaut und der online status auch korrekt wiedergegeben das war die notwendige basis hieran weiter arbeiten zu können.

Zudem hatten wir die frage ob wir wissen ob ein gerät komplett initialisiert ist, es gibt ein event dazu (initialised) diese wird auch im log ausgegeben.
Die sollte erst kommen nachdem alle Entitäten uebertragen wurden, müssten hier mal probieren ob diese event wirklich stabiel ist zu ermitteln ob ein gerät komplett initialisiert ist um damit den cleanup zu starten

**Comment by DutchmanNL** [comment]
ist eingebaut, momentan nur in de branch da ich das lösche der devices noch mit einbauen möchte.
Unnötige channels/states werden 10 Sekunden nach der Initialisierung damit aufgeräumt https://github.com/DrozmotiX/ioBroker.esphome/commit/09bbe1d837385d005ebae4afca01ebde83445579

**Comment by DutchmanNL** [comment]
device cleanup button ist jetzt auch drin, wird mit der niesten release rausgehen
