### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by UncleSamSwiss** [DrozmotiX/ioBroker.esphome#41]
I added the adapter to Weblate, but please make sure you add all strings from `index_m.html` to your JSON translation files. Currently multiple are missing (e.g. "Edit device", "API password", and some more).

**Comment by DutchmanNL** [comment]
thank. you, I didn't notices some are missed would be cool if we can have an alert or automation for that.
Added missing parts :  https://github.com/DrozmotiX/ioBroker.esphome/commit/bee90e8abeb6629e7b117f276ecacaa265d179b9
https://github.com/DrozmotiX/ioBroker.esphome/commit/7e26f9e7a5f67e82a53a0b0788a16ccb96d4a778
