### ISSUE TITLE
Native integration of ESPHome web-front end into adapter instance

### ISSUE THREAD

**Issue by quorle** [DrozmotiX/ioBroker.esphome#47]
**Describe wanted Enhancement !**  
Die Erstellungen der ESPHome Komponennten sollte in ioBroker integriert werden, wie es bei Home-Assistant möglich ist. Dies würde eine neuen, breiten Sektor für alle Benutzer zur Verfügung stellen.

**Why should we put effort in it ?**  
Die Community könnte alles aus einem System verwalten und Programmieren. Egal ob es die eigenen Sensoren, Aktoren sind, oder die mit Javascript erstellte Hauptlogik ist.

**Comment by DutchmanNL** [comment]
habe es mir bereits angeschaut, bissl komplex wegen der Python Abhängigkeit. Mal schauen wie weit wir kommen ich solange ich es nicht aufgegeben habe lasse ich das issue offen :)

**Comment by Apollon77** [comment]
@DutchmanNL hast DU dir mal xbox adapter angeschaut? Vllt kann man es ja mit nopy machen?!

**Comment by DutchmanNL** [comment]
> @DutchmanNL hast DU dir mal xbox adapter angeschaut? Vllt kann man es ja mit nopy machen?!

ich vertiefe mich gerade in die Materie thank fuer den hint. :)

**Comment by DutchmanNL** [comment]
Sneak preview, something is coming there ... :-)

<img width="1513" alt="Schermafbeelding 2021-03-27 om 13 35 29" src="https://user-images.githubusercontent.com/7318445/112720954-b0454100-8f01-11eb-8106-ab492c8814a8.png">

**Comment by DutchmanNL** [comment]
have fun with >= 0.2.x :)

https://github.com/DrozmotiX/ioBroker.esphome/releases/tag/v0.2.0

<img width="1295" alt="dashboard" src="https://user-images.githubusercontent.com/7318445/112943587-f8e34100-9131-11eb-9291-821e5c0f8e76.png">
