### ISSUE TITLE
reconnect Meldungen von error auf warn umstellen 

### ISSUE THREAD

**Issue by santa81** [DrozmotiX/ioBroker.esphome#48]
einer meiner esps verbindet sich ab und zu neu.
Eigentlich ist aber kein error notwendig, ein warn reicht auch.
Zusätzlich sind beim reconnect nicht alle Infos notwendig (also welche states verbunden sind), es würden hier nur neue states reichen.

**Comment by DutchmanNL** [comment]
> Eigentlich ist aber kein error notwendig, ein warn reicht auch.

jup stimme ich zu werde ich ändern



> Zusätzlich sind beim reconnect nicht alle Infos notwendig (also welche states verbunden sind), es würden hier nur neue states reichen.

hmm macht sin ja, momentan lasse ich jede Initialisierung ausgeben das kan ich aber im Arbeitsspeicher abfangen.
Meine sorge dabei ist aber das man neue Sache nicht mitbekommt, zb wegen gleichen Namen ich kan nur auf die Meldung filter wen es dieselbe wird aber fuer was anderen haben wir ein Loch im log ?

**Comment by DutchmanNL** [comment]
kannste mal bitte poste welche Meldungen du meinst, moechte die gerne mal abstimmen und dan filtern damit wir anderen Fehler nicht übersehen

**Comment by santa81** [comment]
`esphome.02021-03-30 05:21:35.270info(7887) ESPHome Device info received for testesphome.02021-03-30 05:21:35.260info(7887) ESPHome client 192.168.2.117 connectedesphome.02021-03-30 05:21:05.229warn(7887) ESPHome client 192.168.2.117 disconnectedesphome.02021-03-30 05:21:05.228error(7887) ESPHome client 192.168.2.117 Error: read ECONNRESET
` 

Es gab noch eine andere error Meldung, die tritt derzeit aber nicht mehr auf und die finde ich mit Handy nicht auf die schnelle. 
merkwürdig ist aber das dieser Fehler nur mit diesem esp32 auftritt, 2 andere esp8266 haben nie einen reconnect.

**Comment by DutchmanNL** [comment]
ok also disconnected und ECONNRESET, danke die hatte ich auch stelle ich um auf warning
Das einlesen lasse ich erstmal so,  sonst fehlt das. auch bei aenderungen

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.esphome/releases/tag/v0.2.1-0
https://github.com/DrozmotiX/ioBroker.esphome/commit/397249d4709d050b43d3109adfbeb3f6e623e3ef

<img width="1499" alt="ESPHome_LoggingImproved" src="https://user-images.githubusercontent.com/7318445/112970961-06f38a80-914f-11eb-8dff-259636d05792.png">
<img width="665" alt="ESPHome_LoggingOptimized" src="https://user-images.githubusercontent.com/7318445/112970965-0824b780-914f-11eb-8660-fcd8c17a0336.png">
