### ISSUE TITLE
Datenpunkt name


### ISSUE THREAD

**Issue by santa81** [DrozmotiX/ioBroker.esphome#49]
Es wäre super wenn der Name vom state der gleiche Name wie der vom übergreifenden channel.
Oder eventuell zusätzlich einen zusammengefügten Namen wie in dem Beispiel also: switch - Relais 1

![Screenshot_20210326-101607_Chrome Beta~2.jpg](https://user-images.githubusercontent.com/18234371/112624969-9c7cda80-8e2e-11eb-95ee-0f815028feb0.jpg)

**Comment by DutchmanNL** [comment]
> wie der vom übergreifenden channel



> Namen wie in dem Beispiel also: switch - Relais 1



eh ja ... was von den beiden sol es. werden ;)

**Comment by santa81** [comment]
Ich persönlich finde den doppelnamen gut, vielleicht hat ja noch jemand anderes ein Meinung dazu.

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.esphome/releases/tag/v0.2.1-0
https://github.com/DrozmotiX/ioBroker.esphome/commit/6e27783fec52d7cc74ab2daf4bb72ec988391634

<img width="1487" alt="ESPHome_StateName" src="https://user-images.githubusercontent.com/7318445/112971085-2a1e3a00-914f-11eb-9e87-a73c2d6f439b.png">

**Comment by wuast94** [comment]
Moin, vlt kann man das ganze Thema nochmal aufräumen, vlt bin ich aus der HA welt anderes gewöhnt oder hab iobroker einfach noch nicht verstanden. Aber die benennung und übersichtlichkeit in io will nicht in meinen kopf

![image](https://user-images.githubusercontent.com/16965460/158990803-a124f79b-7b63-4466-ab6d-0dfa7e3d349a.png)

Ich mein das ist einfach ein esphome device, die liste geht nach unten noch um einiges weiter, angefangen bei der kryptischen id vom gerät selber. Dann ist jedes einzelne reading in einen ordner gepackt der genau so eine kryptische id hat, wo dann das state drin ist. Ich denke meine probleme sind klar. 

Die frage ist für mich was die gründe dafür sind damit ich es verstehen kann. wahrscheinlich bin ich einfach wieder blond und blind 😂

**Comment by DutchmanNL** [comment]
> sind damit ich es verstehen kann. wahrscheinlich bin ich einfach wieder blond und blind 😂

So ist halt die ioBroker Struktur 

Device => Channel ==> State 

Jeder esp ist eine Device (Mac Adresse), jeder config ein Channel und diese können 1 oder mehrere states haben
