### ISSUE TITLE
Updating Adapter lose yaml files

### ISSUE THREAD

**Issue by FredF63** [DrozmotiX/ioBroker.esphome#57]
After updating from 0.2.0.0 to 0.2.1-1 the yaml files in folder /opt/iobroker/node_modules/iobroker.esphome/config are deletet

**Comment by instalator** [comment]
The configuration needs to be stored in the iobroker-data directory. e.g. \ iobroker-data \ zigbee_0 \

**Comment by Apollon77** [comment]
Yes, adapter-core had methoda to get a AdapterCOnfigDir that should return such a "good" path. and best also defint it a Data dir in io-üpackage so it gets included in backup

**Comment by DutchmanNL** [comment]
Solved in [V0.2.2](https://github.com/DrozmotiX/ioBroker.esphome/releases/tag/v0.2.2)
