### ISSUE TITLE
Cannot read property 'deviceInfo' of undefined

### ISSUE THREAD

**Issue by Jey-Cee** [DrozmotiX/ioBroker.esphome#61]
**Describe the bug**  
Error message on log when ESP is not reachable: 
` ESPHome error handling issue 192.168.0.99 TypeError: Cannot read property 'deviceInfo' of undefined`

**To Reproduce**  
1. Disconnect the ESP from Wifi
2. Go to configuration
3. Add the device 

**Expected behavior**  
Only a info message that this device is not rechable.

**Versions:**  
 - Adapter version: 0.2.1-1
 - JS-Controller version: 3.2.16
 - Node version: 14.16.1
 - Operating system: ubuntu

**Comment by DutchmanNL** [comment]
can you please re-test if this is still the case ?

**Comment by Jey-Cee** [comment]
Is fixed
