### ISSUE TITLE
Disabled Auto-Discovery - Modules not checked for adapter start

### ISSUE THREAD

**Issue by ToTXR4Y** [DrozmotiX/ioBroker.esphome#66]
Wenn Auto-Discovery deaktiviert ist, dann werden alle bereits angemeldeten Module auf "nicht verbunden" gesetzt bei Adapter-Start. Ein reaktivieren erfordert einmalig die erneute Eingabe des API Passwortes und abspeichern damit die Module wieder verbunden werden.

**Comment by DutchmanNL** [comment]
fixed in der branch, bei erfolgreichen test mache ich release

```
npm install DrozmotiX/ioBroker.esphome#v0.2.2 --save
```

**Comment by MrRoundRobin** [comment]
Hatte das gleiche Problem. Fix funktioniert bei mir gut 👍🏼

**Comment by DutchmanNL** [comment]
Solved in [V0.2.2](https://github.com/DrozmotiX/ioBroker.esphome/releases/tag/v0.2.2)
