### ISSUE TITLE
Multiple Network Cards - Selection to listen on specified device

### ISSUE THREAD

**Issue by ToTXR4Y** [DrozmotiX/ioBroker.esphome#67]
Szenario:
Mehrere ETH Karten im System vom Adapter

Auswahl:
Welche Netzwerkkarte soll auf die Auto-Discovery hören, oder Option auf "Listen all".

**Comment by DutchmanNL** [comment]
es scheint doch eine Möglichkeit zu geben binding fuel den listener zu machen, werde es bei Gelegenheit testen.implementieren

**Comment by ToTXR4Y** [comment]
Ja das wäre was. Kann das bei Bedarf auch testen, hab ja aktuell 3x ETH integriert für verschiedene Bereiche.

**Comment by DutchmanNL** [comment]
waiting for dependency to solve auto discovery https://github.com/twocolors/esphome-native-api/issues/23
