### ISSUE TITLE
subnetz nicht erkennbar

### ISSUE THREAD

**Issue by arteck** [DrozmotiX/ioBroker.esphome#72]
wenn sich der ESP sich nicht im gleichen Netz befindet wie iobroker ist dieser nicht erkennbar

**Comment by DutchmanNL** [comment]
Danke für die Meldung! Kan der adapter leider nicht fixen, auto discovery läuft über mdns das Netzwerk muss den broadcast weiterleiten.

Für doppelte Netzwerkarte und binding auf richtig ip existiert bereits ein issue

Option A) Netzwerk broadcast relax einrichten

Option B) 2te Netzwerke Karte an ioBroker weiterreichen für den netzwerkbereich

Option C) Device Manuel hinzufügen 

Recconnect für manuelle devices schlägt fehl, Fehler bekannt und fix unterwegs 

Ich verlinke später die existierende issues in diesem befohr ich schließe

**Comment by arteck** [comment]
option a und b sind mehr oder minder vorhanden da sonst andere adapter mit dem sub netz nicht komunizieren würden (sonoff,mqll,wled) ergo daran liegt es nicht

**Comment by DutchmanNL** [comment]
> option a und b sind mehr oder minder vorhanden da sonst andere adapter mit dem sub netz nicht komunizieren würden (sonoff,mqll,wled) ergo daran liegt es nicht

sicher?
macht mal bitte einen MDNS listerner, autodiscovery geht per MDNS, Plans blockieren standard mdns.
snoof, met, wled benutte keinen broadcast

**Comment by DutchmanNL** [comment]
kannste mal bitte mit mdmns-js probieren was bei dir ankommt ? hier das script dazu"

```
var mdns = require('mdns-js');
//if you have another mdns daemon running, like avahi or bonjour, uncomment following line
//mdns.excludeInterface('0.0.0.0');

var browser = mdns.createBrowser();

browser.on('ready', function () {
    browser.discover(); 
});

browser.on('update', function (data) {
    console.log(`data: ${JSON.stringify(data)}`);
});
```

**Comment by DutchmanNL** [comment]
@arteck ?

**Comment by arteck** [comment]
es geht mir nicht um automatische Erkennung.. 
ich muss doch auch eine IP manuell angeben

**Comment by DutchmanNL** [comment]
@arteck hmm ok geht ich glaube jetzt verstehe ich.
Wir haben da noch nen bug das er non-auto connect devices nicht neu verbindet.
Findet er die Device beim manuellen hinzufügen nicht oder nach Adapter Neustart?

Überhaupt garnicht währe neu und müssten wir untersuchen

**Comment by arteck** [comment]
gar nicht..

**Comment by DutchmanNL** [comment]
> gar nicht..

Dan mal zusammen DC bitte kan ich nicht reproduzieren außer das die Device nicht richtig geflasht wurde. Ist im wlan ?

**Comment by arteck** [comment]
geht nicht.... so das ding ist online
![grafik](https://user-images.githubusercontent.com/6681528/119697821-e7c46100-be50-11eb-9bad-4bfa0c285e35.png)

aber nicht verfügbar
![grafik](https://user-images.githubusercontent.com/6681528/119697860-f01c9c00-be50-11eb-983b-a20f2c9d928d.png)

im adapter auch nicht

![grafik](https://user-images.githubusercontent.com/6681528/119697932-01fe3f00-be51-11eb-9e86-bd9de6070671.png)

nein auch nicht nach neustart

**Comment by DutchmanNL** [comment]
Bei ersten Mal findet er ihn sonst kommt er nicht, ist der Bekannte bug beim reconnwct dafür existiert bereits ein issue

das er im ESPHome Dashboard rot ist kan ich nicht ändern, liegt an ESPHome und mdns selber kan man umgehen durch feste ip in der yaml zu hinterlegen, Beispiel : 

`
wifi:
  use_address: 192.168.10.122 `

**Comment by DutchmanNL** [comment]
Siehe Beispiel in Doku

https://drozmotix.github.io/languages/en/Adapter/ESPHome/05.configExample.html#enable-api

![FAB2990F-6AAD-4C26-81CE-6EAED4347525](https://user-images.githubusercontent.com/7318445/119707938-03813480-be5c-11eb-9a71-2b3f32449d74.jpeg)

**Comment by DutchmanNL** [comment]
fixed in der branch, bei erfolgreichen test mache ich release

```
npm install DrozmotiX/ioBroker.esphome#v0.2.2 --save
```

**Comment by arteck** [comment]
mach release
