### ISSUE TITLE
die yaml Datei geht verloren bei Adapter switch im Multihost

### ISSUE THREAD

**Issue by arteck** [DrozmotiX/ioBroker.esphome#73]
wenn ich den adapter von einer Maschiene auf die andere schiebe gehen mir alle Informationen verloren..

diese solltest du irgendwo in ein File ablegen.

**Comment by DutchmanNL** [comment]
Correct danke 👍, ich werde die yaml vom Python Verzeichnis in de ioBroker data Ordner verlegen

**Comment by DutchmanNL** [comment]
fixed in der branch, bei erfolgreichen test mache ich release

```
npm install DrozmotiX/ioBroker.esphome#v0.2.2 --save
```

**Comment by arteck** [comment]
geht
