### ISSUE TITLE
Dashboard does not work through a reverse proxy.

### ISSUE THREAD

**Issue by Anzic23** [DrozmotiX/ioBroker.esphome#75]
**!!! Before you start !!!**  
1. no
2. bug

**Describe the bug**  
Configured the transition to the dashboard via the reverse proxy. The dashboard opens, but when you try to view the logs, or compile the firmware, nothing happens. There are a lot of errors in the console.

**To Reproduce**  
1. Configured the transition to the dashboard via the reverse proxy
2. Click on ' LOGS'
3. Open console in Chrome

**Expected behavior**  
work via a reverse proxy, if possible.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/115844721-cb37a200-a428-11eb-9aa1-988cbb62a350.png)

**Versions:**  
 - Adapter version: 0.2.1-1
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1
 - Operating system: docker

**Comment by DutchmanNL** [comment]
sorry can't fix that please report to ESPHome as this is an issue with the ESPHome python release itself.
I use Nginx Proxy manager and with that it works just fine :)
