### ISSUE TITLE
nach update vom git sind die Geräte weg

### ISSUE THREAD

**Issue by arteck** [DrozmotiX/ioBroker.esphome#97]
na klasse

![grafik](https://user-images.githubusercontent.com/6681528/119698788-e34c7800-be51-11eb-8c3f-e723bf5ed7bc.png)

im adapter ist der nicht connected..

![grafik](https://user-images.githubusercontent.com/6681528/119698896-fc552900-be51-11eb-92ab-64f020a68cd1.png)

korrigiere .. nach erneuter psw eingabe ist der online.. 

wo werden die yaml's gespeichert ??
ich habs ... auf dem jeweiligen host unter 
/opt/iobroker/node_modules/iobroker.esphome/config

dann ist ja klar dass die gelöscht werden...

du musst sicher stellen dass diese ein update überleben...

**Comment by santa81** [comment]
Beide Fehler sind bekannt und schon offen.


https://github.com/DrozmotiX/ioBroker.esphome/issues/57
